### ISSUE TITLE
Folding by 'syntax' does nothing with Markdown syntax

### ISSUE THREAD

**Issue by ryanisaacg** [vimwiki/vimwiki#1009]
Syntax: markdown
Version: `Stable version: 2.5`
Config:
```vim
let g:vimwiki_list = [{ 'path': '~/vimwiki', 'syntax': 'markdown', 'ext': '.txt' }]
hi VimwikiLink cterm=underline ctermfg=DarkBlue
let g:vimwiki_folding = 'syntax'
```
Reproduce:
1. Open a Vimwiki file with some headers, in Markdown syntax
2. Attempt to fold a section
3. `Error: No Fold Found`

**Comment by tinmarino** [comment]
@ryanisaacg nice pick
__Fixed:__ . Please:

1. Rebase to top of dev
2. Check if the issue is still present
3. Close the issue

Thank you for the nice report.

**Comment by tinmarino** [comment]
@devs: An easy issue in theory but I had troubles with test so added many lines.

__Doc removal:__ `:h g:vimwiki_folding`: `'syntax' is only available for the default syntax so far`

* `bullet_types` again hanted me, I realized it with `syn list VimwikiList`: note the `#` that is filtering from default syntax due to a poor heritage of vimwiki_tmp_setting. For markdown `[*, -, +]` is expected but the code reading `bullet_types` <- `s:populate_wikilocal_options` is called at init, so it is too late when Vader is hot chaing the syntax. I move it to `s:normalize_wikilocal_settings` and it realy belongs to `syntaxlocal` options (vimwiki blessing 🤓) 

```
^\s*\%(\(-\|\*\|#\)\|\(\C\%(\d\+)\|\d\+\.\|[ivxlcdm]\+)\|[IVXLCDM]\+)\|\l\{1,2})\|\u\{1,2})\)\)\)\s
```

**Comment by ryanisaacg** [comment]
Thanks for the fix!
