### ISSUE TITLE
Conceal fenced code

### ISSUE THREAD

**Issue by nikinbaidarr** [vimwiki/vimwiki#1012]
Hi, the vimwiki syntax for defining code blocks is amazing.
You place your block of code (or line of code)  within {{{ and }}} and it does the trick just fine.
But when you have a lot of smaller pieces of codes that you want to place inside your vimwiki file, it strains your eyes to see {{{ }}} everywhere. So, I was wondering if there was a way to conceal the fenced code syntax like for the links or bold texts.
For example, when you create a link [[Link]] and you move your cursor some place else the [[ ]] gets concealed and you only see Link. Same for bold texts. We can use *Bold Text* and everything within * * gets formatted into bold text and once you remove your cursor * * gets concealed while the text still renders in bold.
Is there a way to do something similar with fenced code blocks?

**Comment by tinmarino** [comment]
>  Is there a way to do something similar with fenced code blocks?

Yes, in a vim command line:

```vim
syn match VimwikiConceal /^{{{.*\|^}}}.*/ conceal
```

Will hide `{{{` and `}}}` as you want. It is not present in vimwiki. Personaly, I abandonned the (easy) implementation because there is not way to hide (alias conceal) a full line, so you still see the empty line, which is misleading.

Vim is very "What you see is what you get" concerning conceal limitations.

Related: #912 describes that it is (as 2020) impossible to colorize concealed different character with different color.

**Comment by nikinbaidarr** [comment]
@tinmarino Thank youso much! This works just as I wanted.
