### ISSUE TITLE
Diary file-name format

### ISSUE THREAD

**Issue by MahbubAlam231** [vimwiki/vimwiki#1026]
Syntax:
```vim
let g:vimwiki_ext2syntax = {'.md': 'markdown'}
let g:vimwiki_list = [{'path': '~/vimwiki/',
            \'syntax': 'markdown',
            \'ext': '.md'}]
```
Version: Stable version: 2.5

----------

Vimwiki diary's file-name format is `yyyy-mm-dd` (For example: `2020-09-30.md`). Is there a way to change it to `dd-mm-yyyy`?

----------------------
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment]
>  Is there a way to change it to dd-mm-yyyy?

No, it is hardcoded all over [autoload/vimwiki/diary.vim](https://github.com/vimwiki/vimwiki/blob/e2a6b825de72b308c798620ca6e8c9244329f6a6/autoload/vimwiki/diary.vim#L89-L98)

As a regex to identify them and strftime string to generate them.

**Comment by d-a-s** [comment]
I did some work on this in a fork, and have a working prototype that I've been using.

https://github.com/d-a-s/vimwiki/pull/1

There are some limitations/caveats that I'm aware of, and possibly others that I haven't noticed based on my usage patterns. I discuss some of them in the PR description. That's why I didn't submit a PR on the upstream repo.

But if anyone else might find it useful, wanted to put a link here since this was the issue that got me started on my mods in the first place.
