### ISSUE TITLE
Bug: Vimwiki conflicts with other Markdown syntax plugin(s)

### ISSUE THREAD

**Issue by sez11a** [vimwiki/vimwiki#1043]
I have installed Vimwiki in my VimStar (https://github.com/sez11a/VimStar) config. Using either Markdown or Vimwiki syntax, Vimwiki appears to "overtake" the existing Markdown support (https://github.com/plasticboy/vim-markdown) I have installed. Any Markdown file I open, even if Vimwiki is set to use Vimwiki syntax, is seen as a Vimwiki file and Airline doesn't display the word count of the file. 

![image](https://user-images.githubusercontent.com/515497/97315959-a1b60900-183f-11eb-80a8-2fa7b974fcde.png)

My config is very simple: 

```
" Vimwiki Configuration
let g:vimwiki_list = [{'path': '~/Documents/pim/vimwiki/', 'path_html': '~/Documents/pim/wiki_html/'}]
```
Vimwiki is installed via VimPlug and reports this version: `Stable version: 2.5`

Any help in fixing this would be greatly appreciated!

**Comment by tinmarino** [comment]
Add in your vimrc:

```vim
let g:vimwiki_ext2syntax = {}
```

So only files in your ~/Documents/pim/vimwiki/ will be set as vimwiki filetype. But These __must__ be vimwiki otherwise you loose vimwiki mappings.
Also you can load your custom (or plugin) markdown ftplugin in `.vim/ftplugin/vimwiki.vim` and then both coexists (this is not supported => up to you => Ex: I do this with table-mode).

https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/doc/vimwiki.txt#L2652-L2661

**Comment by sez11a** [comment]
That worked perfectly; thank you! I opted for option 1.

**Comment by tinmarino** [comment]
>  I opted for option 1.

God choice, I once opted for option 2 (mixing plugin) and then your configuration gets impossible to debug.
