### ISSUE TITLE
Link with "ssh:" opens Google Chrome

### ISSUE THREAD

**Issue by mgarort** [vimwiki/vimwiki#1060]
### System info ###
Vimwiki version: Stable 2.5
OS: Ubuntu 18.0 with i3wm tiling manager
Syntax: default Vimwiki syntax
### End of system info ###

Hello,

This behaviour has me very confused. I don't know what to think.

In my system, if you create a link `[[ssh:]]`, instead of following the link and creating a Vimwiki file called `ssh:.wiki`, it opens Google Chrome. Wait, what???

Yes. It opens Google Chrome.

This DOES NOT happen with:
- `[[ssh]]`: following this link will create a file callled `ssh.wiki`.
- `[[ssh :]]`: following this link will create a file called `ssh :.wiki`.
- `[[bogusname:]]`: following this link will create a file called `bogusname:.wiki`.

This DOES happen with a longer link, as long as it starts with `ssh:`:
- `[[ssh: Rest of link]]` opens Google Chrome. Wait, what???

I would be grateful for any pointers explaining what could be happening under the hood. Searching "ssh" in the Vimwiki documentation doesn't bring up anything. I am dumbfounded.

Thanks in advance.

**Comment by thecliguy** [comment]
Does this behaviour only occur when the i3wm tiling manager is used?

**Comment by mgarort** [comment]
Hi @thecliguy I only use i3wm, so I don't know if it happens in other environments or not. Maybe other people can try in their systems and let us know.

**Comment by thecliguy** [comment]
I've done some testing and concluded that this behavior is because VimWiki treats `ssh:` as a URI scheme type:

```
:echo vimwiki_global_vars.web_schemes1

http\|https\|file\|ftp\|gopher\|telnet\|nntp\|ldap\|rsync\|imap\|pop\|irc\|ircs\|cvs\|svn\|svn+ssh\|git\|fish\|sftp
```

This results in the link being passed to `vimwiki#base#system_open_link` where the operating system determines the application that's responsible for handling the `shh:` URI, which in your case must be Google Chrome.

I think there are two possible solutions to this...
1.   Escape the `[[ssh:]]` link so VimWiki doesn't treat `ssh:` as a URI scheme type. But I don't actually know if VimWiki has an escape syntax that can do this... Someone more familiar with the VimWiki codebase will have to comment on this.
2.   If you don't mind losing the ability to open `ssh:` links with the operating system's associated application (in your case Google Chrome) then you could remove `ssh` from the `web_schemes1` list. I don't actually know the best way to accomplish this, so again someone more familiar with the VimWiki codebase will have to comment on this.

@vimwiki/contributors Is anyone able to comment on the points above?

**Comment by mgarort** [comment]
Hi @thecliguy thanks a lot for your investigation! This makes a lot of sense.

I don't know if there is a correct way to fix it (I will wait for the developers to comment on that), but I have temporarily avoided the issue by manually removing `'ssh'` from the variable `g:vimwiki_global_vars.web_schemes1` in the file `.vim/bundle/vimwiki/autoload/vimwiki/vars.vim`.

I would actually be very interested to know if there's a more elegant way to modify the variables defined in this file, since I use my own highlight task actions (just like `TODO`, `DONE`, `XXX`... I also like to highlight `QUESTION`, `ANSWER`, `NOTE`...) in Vimwiki. These are defined in `g:vimwiki_global_vars.rxTodo`, which I have also manually modified in `vars.vim`.

Maybe the most elegant way is to redefine these variables in a file in `.vim/after`?

**Comment by tinmarino** [comment]
Hi @mgarort,

As @thecliguy said: the `ssh:` prefix is leading to `vimwiki#base#system_open_link` (-> `xdg-open` on Linux).
This is the desired behavior. But usually system do not have a way to open ssh mime type.

So the default behavior should not change but it is harcoded in [g:vimwiki_global_vars.web_schemes1](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/vars.vim#L41-L43) and that can be changed so that you don't have to maintain a patch.

Do you want to access a file with filename `ssh:why_not` ? (I'm not sure it is possible)

## Other ticket

You pointed me out some bugs with `scp` handler that should open a file like `vim scp://USER@HOSTNAME//etc/passwd` and an other one with `file:` and documentation because you should have the possibility to open 1/ any filename,  2/ anywhere, 3/ any protocol.

This is big, I will follow in #958


## Demo ssh usecase on Ubuntu

write file: `~/.local/share/applications/ssh.desktop`
```desktop
[Desktop Entry]
Version=1.0
Name=SSH Launcher
Exec=bash -c '(argument="%U"; ssh "${argument:4}")'
Terminal=true
Type=Application
Icon=utilities-terminal
````
```bash
ssh $USER@$HOSTNAME
````
```markdown
[ssh test](ssh:$USER@$HOSTNAME)
```

**Comment by mgarort** [comment]
Hi @tinmarino , thanks for the reply.

Yes, I want to open files called `ssh: why_not`. The reason is that I use vimwiki to write notes about everything, and I've written some about `ssh` itself. The title format for these notes is `ssh: Note title`. I have fixed it though by manually modifying `g:vimwiki_global_vars.web_schemes1` as described above. So as far as I'm concerned this is not a problem for me anymore :)  Please feel free to close the issue if you prefer to continue the discussion in #958

**Comment by tinmarino** [comment]
Will you have to maintain a path or can that just be in your vimrc?
Let's close that when you dont have to keep your own vimwiki branch.

**Comment by mgarort** [comment]
Yes, I have to maintain a path, unfortunately... I keep a modified version of `vars.vim` in a personal file called `.vim/own/vars.vim`, and I have a soft link to this file in `.vim/bundle/vimwiki/autoload/vimwiki/vars.vim`.

However, this doesn't seem to be a bug as much as a design choice. There will be people, like me, who want to start a filename with `ssh:`, but I can imagine other people wanting to write an URI that starts with `ssh:`. If the latter, the current behaviour seems appropriate.

Maybe the best option would be to allow the user to define `g:vimwiki_global_vars.web_schemes1` in their `vimrc`? (And also `g:vimwiki_global_vars.rxTodo`, in order to highlight custom words like I described above?)

**Comment by tinmarino** [comment]
@mgarort 

I just did the easy part: make that configurable to keep you on the `dev` code. Please update the dev branch and add something like that:

```vim
let g:vimwiki_schemes_web = ['http', 'https']
let g:vimwiki_rx_todo = '\C\<\%(QUESTION\|ANSWER\|NOTE\|TODO\|DONE\|STARTED\|FIXME\|FIXED\|XXX\)\>'
```

If that does not work, reopen the ticket. I'll add some non-regression test and, one day refactor base.vim keeping all those functionalities.


Continued in  #958
