### ISSUE TITLE
changing vimwiki index path

### ISSUE THREAD

**Issue by linuxdotexe** [vimwiki/vimwiki#1130]
Prior to submitting a new issue make sure to complete these steps:

- [ ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

I am trying to change the default path. It creates a folder in my home directory even though I specified the below in my config:
```
vim.cmd("let g:vimwiki_list = [{'path': '~/hdd/wiki/'}]")
```
A new empty index.wiki gets created at ~/vimwiki inspite of this setting. I am not sure what I am doing wrong. Please help.

Using neovim nightly, default syntax.

VimwikiShowVersion Output:
```
Stable version: 2.5
```

**Comment by tinmarino** [comment]
A bug from Vimwiki.

The local variable 'path' should have been updated : https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/vars.vim#L352

Ensure somehow to set this var so that `:VimwikiVar path` gives you the corect thing (suprinsingly it dit return ~.vimwiki for me too)

**Comment by cvicentiu** [comment]
In case this helps anyone, I encountered this bug when placing the lua config in `~/.config/nvim/after/plugin/vimwiki.lua`
### Workaround:

Placing the config in `~/.config/nvim/lua/vicentiu/init.lua` after all other package loads happened, made VimWiki respect "path".

**Comment by tinmarino** [comment]
Yes, Thank you @cvicentiu 

The path must be specifyied __before__ loading the vimwiki package as every vimwiki configuration, (so not in after files) and the dev branch must be used. Then I got:

```vim
:VimwikiVar path
Vimwiki: Got: path = '/home/mtourneb/wiki/wiki/'   " <= From: Wikilocal
```

And output updates correctly according to the wiki used => Closing

**Comment by annahri** [comment]
I tried to setup vimwiki using `lazy.nvim`, and after spending hours, the `:VimwikiVar path` was always returning the default path, which is `~/vimwiki`. 

In the end, I tried to enter `:VimwikiIndex`, and turns out it uses the path I've setup, even the `:VimwikiVar path` returns the default.

I've lost my mind but at least it's working now.

**Comment by aaharr** [comment]
I wanted to link [this issue](https://vi.stackexchange.com/questions/43446/configuring-vimwiki-in-neovim) for other LazyVim users thrashing about (Looking at you future self).

To be explicit, the trick is to define the `init` function in your spec to define the path, not `config`, as this is the lazy.nvim way of keeping the init chores alongside the rest of the spec.
