### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ches** [vimwiki/vimwiki#114]
Only one (accidental) commit has been pushed to the master branch of this repository since mid-2013, but a bunch of stuff has been done on the `dev` branch. Could we get an update on the state of the project? Has @habamax blessed some new people as official co-maintainers? What are the goals on the `dev` branch and what are the criteria for when that work will be merged to master? It'd be a good idea to answer some questions like these on the master branch's README, don't you think?

As an aside, I wish when the vimwiki Github organization was set up that this repo had been imported from Mercurial with hg-git instead of forking the vim-scripts repo with woefully incomplete commit history, but alas...

**Comment by EinfachToll** [comment]
Well, good question. The main feature I wanted for the next release is support for anchors. Now that @t7ko came up with tags (see #85), this should be included before the next release as well, because it interferes in some ways with anchors.

> Has @habamax blessed some new people as official co-maintainers?

No, he just stopped contributing some time ago. That's no problem, because I and some other people have full rights to this repository. When we make a release, I will contact him so that we can also update Vimwiki's home at http://www.vim.org/scripts

**Comment by ches** [comment]
Great, thanks for your response! It sounds like a forthcoming release would be a good time to publish a contributing guide that gives people some idea of what to expect, if there's some semi-regular activity on the project and some guiding direction on process.

I've just started using the dev branch yesterday, happy to see some of these features and fixes, thanks for your work :smiley:

**Comment by positron** [comment]
I also would consider contributing if there was a CONTRIBUTING.md

**Comment by t7ko** [comment]
@positron what information would you need to start contributing?  Ask here.  And then your first contribution can be creating CONTRIBUTING.md!

**Comment by t7ko** [comment]
Technically, it's simple:
* fork vimwiki repo
* branch off of the `dev` branch
* implment whatever you want to
* create pull request.

**Comment by EinfachToll** [comment]
@positron There is a section about contributing in the help file.
