### ISSUE TITLE
Setting 'let g:vimwiki_toc_header_level = 2' includes level 1 headers in the table of contents

### ISSUE THREAD

**Issue by jakec-dev** [vimwiki/vimwiki#1159]
In `.vimrc`, add the following line:

`let g:vimwiki_toc_header_level = 2`

Then create a basic wiki page such as:

```
# Page Heading - Level 1 Heading

## Contents

## Level 2 Heading
foo

### Level 3 Heading
bar

## Level 2 Heading (2)
foo foo

### Level 3 Heading (2)
bar bar
```

Now save the file. It will return the following under `## Contents` section:

```
## Contents

- Page Heading - Level 1 Heading
    - Level 2 Heading
        - Level 3 Heading
    - Level 2 Heading (2)
        - Level 3 Heading (2)
```
This is not the expected behaviour. It should instead return:
```
## Contents

- Level 2 Heading
    - Level 3 Heading
- Level 2 Heading (2)
    - Level 3 Heading (2) 
```
There is no reason for H1 headings to be included in a table of contents as there is only ever 1 H1 tag per page (as per best practices). The default procedure should be to follow best practices, and if this causes issues for anyone using multiple H1 tags per page then perhaps include an option for them to disable this feature.

**Comment by brennen** [comment]
> This is not the expected behaviour.

The expected behavior for `g:vimwiki_toc_header_level` is to set the header level of the rendered table of contents itself, which it does.  It is not, as far as I can tell, expected to filter the table of contents itself. We could probably improve the documentation a bit.

> There is no reason for H1 headings to be included in a table of contents as there is only ever 1 H1 tag per page (as per best practices).

Whether it's a best practice on the web or no, I don't think this is an especially safe assumption.  Many web pages do contain multiple `<h1>` headers.  Similarly, I imagine a number of people use multiple top-level headers within VimWiki pages.  I do so myself on probably a few hundred pages.

Current behavior also supports rendering the TOC at various points within the file - a link to the anchor for even a single top-level heading can be quite useful for navigation with a long TOC.

> The default procedure should be to follow best practices, and if this causes issues for anyone using multiple H1 tags per page then perhaps include an option for them to disable this feature.

TOC-generation is already fairly complicated and glitch-prone code, and introducing yet another configuration path will only make it more so.  Further, I'd rather not have to explain to new users why section headings aren't showing up in their TOC unless they adjust configuration.

I'd review a PR that implements a separate option for filtering the TOC by header level (see  `vimwiki#base#update_listing_in_buffer()`), but I can't say I'm in favor of one.
