### ISSUE TITLE
Can't fold list items

### ISSUE THREAD

**Issue by asldjkv** [vimwiki/vimwiki#117]
With [vimwiki](https://github.com/vim-scripts/vimwiki) you can fold headers and lists as following:

Example for headers and list folding:

```
= My current task =
  * [ ] Do stuff 1
    * [ ] Do substuff 1.1
    * [ ] Do substuff 1.2
      * [ ] Do substuff 1.2.1
      * [ ] Do substuff 1.2.2
    * [ ] Do substuff 1.3
  * [ ] Do stuff 2
  * [ ] Do stuff 3
```

Hit <kbd>zM</kbd>:

```
= My current task = [8] --------------------------------------
```

Hit <kbd>zr</kbd>:

```
= My current task =
  * [ ] Do stuff 1 [5] --------------------------------------
  * [ ] Do stuff 2
  * [ ] Do stuff 3
```

Hit <kbd>zr</kbd> one more time:

```
= My current task =
  * [ ] Do stuff 1
    * [ ] Do substuff 1.1
    * [ ] Do substuff 1.2 [2] -------------------------------
  * [ ] Do substuff 1.3
  * [ ] Do stuff 2
  * [ ] Do stuff 3
```

The header-folding does works for me, but list-folding as underneath doesn't:

```
= My current task =
  * [ ] Do stuff 1 [5] --------------------------------------
  * [ ] Do stuff 2
  * [ ] Do stuff 3
```

Vimwiki says this about list-folding, but I don't understand what it exaclty means:

> NOTE: If you use the default vimwiki syntax, folding on list items will work
> properly only if all of them are indented using current shiftwidth.
> For MediaWiki, `*` or `#` should be in the first column.

My vimrc is as following:

```
Plugin 'vimwiki'
set nocompatible
filetype plugin on
syntax on
set foldmethod=syntax
```

**Comment by asldjkv** [comment]
Update: 

I've added the following to my .vimrc

    let g:vimwiki_folding = 'list'

This had the result that headers and list couldn't be folded.

**Comment by EinfachToll** [comment]
That you can only fold headers as you describe in your first post, can be explained by the line

    set foldmethod=syntax
in your vimrc. It lets Vim (not Vimwiki) figure out foldable regions based on the syntax.

The line you added as you wrote in your second post should normally cause Vim to fold list items. For me, it works. What is your output for `:set foldmethod?` ?

The note in the doc you don't understand says that folding of lists will work properly only if all subitems of an item are indented by 'shiftwidth', which is the width a line is moved by when you press << or >>. Its default is 8, so consider setting it to e.g. 4.

But you didn't really say what your problem is. Do you want to be able to fold headers as well as list items? I suspect that doesn't work at the moment. You can still use the text objects Vimwiki provides to fold a region manually. So, `zfah` creates a fold of the current header and `zfal` folds the current list item (if you use the dev branch of this repo).

**Comment by asldjkv** [comment]
Thank you for your reply. I've added the setting let `set g:vimwiki_folding='list'` , and removed the setting set `set foldmethod=syntax`. As result of this, I can now fond and unfold list items when created by **Shift+>>**. Unfortunately, the headers are now the ones who can't fold and unfold. My output by `:set foldmethod?` is `foldmethod=expr`. 

I want to be able fold headers as list-items as wel. 

This is my entire .vimrc:

    set nocompatible              " be iMproved, required
    filetype off                  " required
    
    " set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    " alternatively, pass a path where Vundle should install plugins
    "call vundle#begin('~/some/path/here')

    " let Vundle manage Vundle, required
    Plugin 'gmarik/Vundle.vim'
    
    " vimwiki - Personal Wiki for Vim - http://vimawesome.com/plugin/vimwiki-you-belong-with-me
    Plugin 'vimwiki/vimwiki'
    " required settings
    set nocompatible
    filetype plugin on
    syntax on
    " additional settings
    let g:vimwiki_folding='list'
    
    " All of your Plugins must be added before the following line
    call vundle#end()            " required
    filetype plugin indent on    " required
    " To ignore plugin indent changes, instead use:
    "filetype plugin on
    "
    " Brief help
    " :PluginList       - lists configured plugins
    " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
    " :PluginSearch foo - searches for foo; append `!` to refresh local cache
    " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
    "
    " see :h vundle for more details or wiki for FAQ
    " Put your non-Plugin stuff after this line>'
PS
I'm using vimwiki master.

PSS
I don't know if this information can be helpful: 
I'm using vim 7.4 in gnome-terminal with ubuntu 14.04

**Comment by EinfachToll** [comment]
Well, seems like it's not possible at the moment.

**Comment by asldjkv** [comment]
Are there any chances for a bug-fix for this issue in the nearby future?

**Comment by EinfachToll** [comment]
Not from my side, I'm afraid, since I'm short of free time at the moment.
Also, I haven't touched the code related to folding much, so probably I don't have more knowledge than you, which means that you can easily take over the task yourself, if you want ;)

The relevant code would be this:
https://github.com/vimwiki/vimwiki/blob/dev/ftplugin/vimwiki.vim#L140-L161
https://github.com/vimwiki/vimwiki/blob/dev/plugin/vimwiki.vim#L227-L244

**Comment by ranebrown** [comment]
This looks like more of an enhancement than a bug and the desired results should be possible by using `g:vimwiki_folding = 'custom'`.
