### ISSUE TITLE
Support for mixing `.md` and `.markdown` file extensions?

### ISSUE THREAD

**Issue by tompropst** [vimwiki/vimwiki#1208]
I have a large collection of markdown files that I am trying to organize into a vimwiki but they have a mixture of `.md` and `.markdown` file extensions. I could globally rename them however they also have relative links in them already.

Everything I've seen indicates that vimwiki will use just a single file extension when performing actions such as `:VimwikiGenerateLinks`. What I am currently seeing is that a file named with `.markdown` will have `.md` in an auto-generated link (and hence the link will not work).

My relevant `.vimrc`:

```
" Settings for vimwiki
" Using `dev` branch to make auto index features work with folding on.
let g:vimwiki_global_ext = 0
let wiki_1 = {}
let wiki_1.path = '~/notes/'
let wiki_1.diary_rel_path = 'journal/'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.md'

let g:vimwiki_list = [wiki_1]

" This line was needed for things like table formatting to work
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown'}
let g:vimwiki_dir_link = 'index'
let g:vimwiki_folding = 'expr'
" This line required to append file extension in markdown links
let g:vimwiki_markdown_link_ext = 1
```

**Comment by brennen** [comment]
> I have a large collection of markdown files that I am trying to organize into a vimwiki but they have a mixture of .md and .markdown file extensions. I could globally rename them however they also have relative links in them already.

My honest answer here is that you should rename the files to something consistent and do a search-and-replace for the links, but this is also the first time I'm learning that `g:vimwiki_ext2syntax` exists.

On reading the help text, I don't think this is intended to let you mix file extensions within a single wiki:

```
*g:vimwiki_ext2syntax* *vimwiki-register-extension*

A many-to-one mapping between file extensions and syntaxes whose purpose is to
register the extensions with Vimwiki.

E.g.: >
  let g:vimwiki_ext2syntax = {'.md': 'markdown',
                  \ '.mkd': 'markdown',
                  \ '.wiki': 'media'}

An extension that is registered with Vimwiki can trigger creation of
a |vimwiki-temporary-wiki|. File extensions used in |g:vimwiki_list| are
automatically registered with Vimwiki using the default syntax. Extensions
mapped with this option will instead use the mapped syntax.

Default: >
    {'.md': 'markdown', '.mkdn': 'markdown',
    \  '.mdwn': 'markdown', '.mdown': 'markdown',
    \  '.markdown': 'markdown', '.mw': 'media'}

Note: setting this option will overwrite the default values so include them if
desired.
```

I think this is, in practice, mostly for making VimWiki aware of those extensions for creating temporary wikis. While I have not gotten into the code, I don't _think_ it provides for mixing extensions within a wiki, which at any rate seems like the kind of thing we shouldn't be supporting because it will add complexity to the implementation for a corner case needed by very few users. The docs could probably be clarified here.
