### ISSUE TITLE
How to let vimwiki open internal en external files?

### ISSUE THREAD

**Issue by hrrybrwn** [vimwiki/vimwiki#132]
Hi guys,

I would like that vimwiki opens files with its default program when pressing enter on the link.

I've read the *VimwikiLinkHandler*, but I didn't succeed to understand how to use it.

I would be grateful if someone could give me an example how to open the following filetypes with their software:

urls > firefox
spreadsheet > libreoffice
pdf > evince

PS
I'm using the dev branch.

**Comment by EinfachToll** [comment]
For the base case you don't need the VimwikiLinkHandler, you can just make a link `[[file:/path/to/your/file.pdf]]`. The file is opened on Linux using xdg-open. See `:h vimwiki-syntax-schemes`. URLs are even simpler, see `:h vimwiki-syntax-links`.
But this part concerning links is currently worked on by me (well, the last weeks I didn't find really time), so there might be some changes in the future.

**Comment by hrrybrwn** [comment]
@EinfachToll 
Thank you for your reply. The final solution to this was to install the package `xdg-utils`, which I didn't have on my bare linux configuration.

I appreciate you keeping my most loved plugin alive.

**Comment by horror-vacui** [comment]
I have a similar problem. Hitting enter on a file link in normal mode does not open the link, but it moves to the next line. How could I solve or debug the issue? I do not know where to look at.

**Comment by EinfachToll** [comment]
Moving to the next line is the normal Vim behavior, so my first guess would be that Vimwiki is not installed correctly. Do normal wiki links work? Do you see highlighting?

**Comment by EinfachToll** [comment]
I don't really have an idea. Can you post all your Vimwiki related settings or even your whole vimrc?

**Comment by horror-vacui** [comment]
You can find my vimrc at 
https://github.com/horror-vacui/vimconfig/blob/master/.vimrc

**Comment by mareq** [comment]
I have similar problem: I need to create a link to a non-wiki file, which is handled by another vim plugin (vim-rest-console in this case, but the same principle should apply to generic use-case). If I got it correctly, my current options are:

- create link `[[rest-api.rest|REST API]]` which vimwiki would not like: it marks it in red as non-existent target and when opened, it forces vimwiki filetype, which is wrong (vim-rest-console plugin has its own filetype that needs to be set correctly for it to work)

- create link `[[file:rest-api|REST API]]` which will now be correctly marked as having existing target, but it opens using `xdg-open`, i.e. opens completely separate gvim window, even though I am clicking on it inside nice console-based vim.

It would be nice to have a way how to open links to non-wiki files exactly the same way as links to wiki files (in the very same window of very same vim instance) instead of `xdg-open`, just do correct filetype according to the file's extension and not mark links as having non-existent targets.

Am I missing something and it is indeed possible to achieve what I need? If not, would it be possible to provide such functionality? Thx.

**Comment by tinmarino** [comment]
Are you on the dev branch ? This should open as a .rest file.

**Comment by mareq** [comment]
@tinmarino good point, thanks: I was on `619f04f` (v2.5). After switching to `8d4cb7f` (dev), it (almost) works: link opens exactly as I wanted (in the same window with the correct filetype). The only (cosmetic) issue is that the link colour is `VimwikiNoExistsLink` - while it would have been nice for colours to work as well, I can live with it. Thanks! :+1:
