### ISSUE TITLE
Wikilinks inside <pre></pre>

### ISSUE THREAD

**Issue by f4t-t0ny** [vimwiki/vimwiki#134]
Hi, 

i like to embed ascii graphics inside vimwiki, which i insert with '{{{' which get pre-tags after html conversion. Now i'd love to be able to put (external or internal) links into my ascii graphics, which in general is possible in html inside pre. However, vimwiki ignores links created inside '{{{ }}}'. 

Would it be much of an effort to implement this in the next vimwiki version?

**Comment by EinfachToll** [comment]
Actually, links inside `{{{ }}}` work like everywhere else except that they won't get highlighted and they aren't converted to HTML links. But the fact that they work is more an accident, because it would be difficult to prohibit that.

Honestly, I don't see a reason to allow other syntax elements inside preformatted text, because the very sense of preformatted text is to not format its content. I don't know why links and many other elements are allowd in the HTML pre tags, maybe because in HTML there are other means to escape a HTML tag. But in Vimwiki, we have plain text where we have to make a compromise on what goes. And I think, links in preformatted text is a too special special case.
