### ISSUE TITLE
store wiki in git

### ISSUE THREAD

**Issue by schmeisers** [vimwiki/vimwiki#139]
This is a feature request for a configuration option to store a wiki in a git repository with all file modifications automatically committed.

**Comment by linuxcaffe** [comment]
+1
yes please!
djp

**Comment by EinfachToll** [comment]
When exactly do you want a commit? Every time a file is saved? Once a day? Once a week? With a key press? I think this is something users can easily set up for themselves.

**Comment by schmeisers** [comment]
I want a commit every time a file is saved in order to have a complete history of the wiki.

I've looked into setting this up external to vimwiki.  On Linux there is inotify, but I don't see an easy way to do it on FreeBSD of MacOS.

**Comment by EinfachToll** [comment]
You can use an autocommand like BufWritePost in Vim for that. If a file is written, it would check if the file is actually a wiki file and if so, call git commit or whatever.

**Comment by bmedicke** [comment]
I don't think this should be part of vimwiki. This could be easily accomplished outside of vimwiki or even vim. @schmeisers I would use [fswatch](https://github.com/emcrisostomo/fswatch) which works as a wrapper around FSEvents (MacOS), inotify and kqueue (BSD).

**Comment by elken** [comment]
I agree this isn't functionality that vimwiki should be responsible for. There are *plenty* of alternatives, ie watch, guard, or use a 3rd party hosting site like MEGA, or better still something decentralized like syncthing.

**Comment by EinfachToll** [comment]
Yes, or simply an autocommand ;)

**Comment by guakamole** [comment]
Could someone provide an explanation/links on how to implement this on Linux?
Everytime a change happens in ~/vimwiki/ (except for ~/vimwiki/.git/ obviously), commit it.

**Comment by elken** [comment]
@guakamole you're attempting to loosen a screw with a hammer. Use something like Google Drive and cryptomator (if you're paranoid) or syncthing (if you're super paranoid).

**Comment by Nudin** [comment]
I use vimwiki with git since years. I use GitGutter to have a visual marking of what is not committed yet and vim-fugitive for Committing and Pushing.
I got a vim-filetype-plugin (.vim/after/ftplugin/vimwiki.vim) with the following:
```
:command! W w | execute "Gcommit -a -m 'update'" | Gpush | GitGutter
:command! WQ w | execute "Gcommit -a -m 'update'" | Gpush | q
```
so I use `:w` for only saving to disk and `:W` for saving, commiting and pushing to pull changes mad on another computer I use `:Gpull`.

If you wish to have it committed on every change do something like (untested):
```
function commit()
  w
  execute "Gcommit -a -m 'update'"
  Gpush
endfunction

autocmd BufWritePost * call commit()
```

**Comment by guakamole** [comment]
Hello,

@elken so, what is better? opening a new issue that will get closed because it's a duplicate of this one and/or virtually increase the burden of the pile of new issues?

And it's no about being paranoid or not. Paranoia is a medical condition.

It's about being in control (version control - pun unintended) and KISS. Why would I want to use a cloud solution when all I need is version control (not that it wouldn't be useful, it could be complementary)?

[password-store](https://www.passwordstore.org/) (go check it if you don't know this tool yet), for instance, has built-in optional git hooks which makes it super easy to use. You virtually have nothing to do, just use the tool and it takes care of the versioning (simply using git underneath). Cross-platform.

I know that the maintainer is overwhelmed as of now and that there are, rightfully, other priorities ; so, I wouldn't suggest implementing it but that's definitely something that would add-up nicely to the features of vimwiki (after all, don't most wiki softwares provide version control or records of some sort?)

@Nudin thank you for your answer :)

Could this be hooked to the default vimwiki behaviour somehow? vimwiki automatically saves the changes either when navigating between files or simply `:q` it. What about new directories? Looking for a solution, I stumbled around `gitwatch` and the likes but these solutions seems - maybe wrongfully - pretty hackish to me.

**Comment by Snaptags** [comment]
@Nudin when using vim-fugitive you may want to modify your plugin to use Gwrite:

(.vim/after/ftplugin/vimwiki.vim) 
```
:command! W execute "Gwrite | Gcommit -a -m 'update'" | Gpush | GitGutter
:command! WQ execute "Gwrite | Gcommit -a -m 'update'" | Gpush | q
```

Your solution will never commit or push NEW files, because they are untracked…
