### ISSUE TITLE
Run at startup

### ISSUE THREAD

**Issue by smasher816** [vimwiki/vimwiki#143]
If I use `autocmd VimEnter * if argc() == 0 | execute 'VimwikiIndex' | endif` then the vimwiki opens at startup but links are not parsed and show `[[Link]]`, additionally the filetype does not appear to be set and binds do not work. If I instead use `vim -c "VimwikiIndex"` then the links still display incorrectly however the filetype is set to vimwiki and pressing enter to follow links works. When manually running `:VimwikiIndex` after startup then everything works as expected. I assume these discrepancies are due to issues in the way vim and plugins are initialized.

Note: I am using the dev branch through vim-plug

**Comment by EinfachToll** [comment]
Strange, when I try your first snippet, syntax and everything works. I only get some errors when I follow a link. The reason seems to be that the BufEnter and BufWinEnter autocommands are not triggered for index.wiki.
`vim -c VimwikiIndex` works for me without errors or incorrect highlight.

I also think the reason is the order in which plugins are loaded and commands are executed. Maybe you can try another plugin manager. I'm using Pathogen, btw.
But it seems more like a bug (or multiple bugs) in Vim. `vim -c VimwikiIndex` should normally work.

**Comment by EinfachToll** [comment]
Feel free to reopen if the problem persists.
