### ISSUE TITLE
question: how can I use a definition :: ?

### ISSUE THREAD

**Issue by linuxcaffe** [vimwiki/vimwiki#155]
In the docs under 5.5 Links, there is a brief description of 
<pre>
Definition lists:
  Term 1:: Definition 1
  Term 2::  
  :: Definition 2 
  :: Definition 3  
</pre>
but I've never seen them referred to anywhere else, and I'm trying to guess how I might use them.

I'd like to try and hack together an GenIndex for taskwiki (vimwiki+taskwarrior). My files have a block of definitions, including
<pre>
Description ::  Foo project development wiki
</pre>
So my question is; how might I query for that Description? from vimscript? from bash?
thanks!

**Comment by hpincket** [comment]
I wrote an awk(bash) script for extracting definitions. I don't know if it's along the lines of what you're looking for.

https://github.com/vimwiki/utils/pull/7

**Comment by linuxcaffe** [comment]
That looks like JUST the ticket! thanks! Is that the same as https://github.com/hpincket/vimwiki-definitions-extractor?

My hack is a bash script, so that's great, and I'd like to "extract" the definition to a $DESC variable, instead of outputting to a file, do you have any suggestions for that? (caveat: I'm a terrible programmer ;-)

ps, I'm going to close this issue (answered) but continue this thread, cool?

**Comment by hpincket** [comment]
The version in the pull request is a minor step ahead I believe, otherwise they are the same.

I'm pretty terrible at bash, but looking [here](http://stackoverflow.com/questions/18648345/saving-awk-output-to-variable) it seems you could wrap the whole thing in a $(). I do something like this to get the `now` date variable. You'd want to remove the output redirects (`>>`), in its current state the script splits the output into different files.

**Comment by linuxcaffe** [comment]
cool, thanks!
