### ISSUE TITLE
vimwiki hijacks all help commands

### ISSUE THREAD

**Issue by HeroicAutodidact** [vimwiki/vimwiki#159]
If I type `:help <any other feature unrelated to vimwiki> `

I am redirected to the vimwiki docs, even if I'm not in vimwiki

**Comment by EinfachToll** [comment]
Very strange. Normally, Vim looks in all files in the subdirectory doc/ in all directories in 'runtimepath'. In all these doc/ directories, there must be .txt files with the content and a file called 'tags'. You can rebuild the tags of the official Vim help files with `:helptags $VIMRUNTIME/doc`. (Maybe you have to start Vim using sudo, because you need write permission.)
If this doesn't help, does the output of `:set runtimepath?` look normal? How did you install Vimwiki? Maybe you messed things up while installing.

**Comment by EinfachToll** [comment]
Feel free to reopen if the problem persists.
