### ISSUE TITLE
Outsource diary functionality

### ISSUE THREAD

**Issue by matthiasbeyer** [vimwiki/vimwiki#167]
This is debatable.

I think it would be appropriate to outsource the diary functionality into another vim plugin (do one thing only, but do it well).

Wiki and diary are not necessarily related IMHO.

**Comment by EinfachToll** [comment]
If I had started Vimwiki, I probably would have separated them. But I suspect that many people would have come up with cool ideas how to integrate Vimwiki and the diary plugin ;)
I think we leave it as it is, because
- from the feedback I get I see that many users do use the diary
- the diary code is not exactly the biggest part of Vimwiki
- the diary stuff is relatively tightly integrated into the rest, i.e. the diary plugin would need nearly all fetures and code of the wiki plugin
