### ISSUE TITLE
Issues rendering markdown into html

### ISSUE THREAD

**Issue by AdamKing0126** [vimwiki/vimwiki#216]
I haven't fully tested all markdown, some of them work.  Key markdown tags do not, for example [google it](http://www.google.com)  does not render a link with the text 'google it'.  Also, code blocks aren't working for me, either with tildes or back ticks.  Those characters appear in the rendered HTML document.

I've attached an example:

[vimwiki.txt](https://github.com/vimwiki/vimwiki/files/310474/vimwiki.txt)

**Comment by vcavallo** [comment]
@AdamKing0126 Are you trying to render `markdown` syntax (as in, you've set your configs to use `syntax: 'markdown'`) to HTML? Sorry if I'm misunderstanding you, but that isn't supported.

**Comment by AdamKing0126** [comment]
Yeah sorry for the misunderstanding, there's probably something I am
missing.

I'm using the command :VimwikiAll2HTML to render the wiki to HTML pages

**Comment by vcavallo** [comment]
Are you actually getting markdown syntax to render to HTML? As far as I can tell that's unsupported - meaning the `:VimwikiAll2HTML` command shouldn't work at all. I opened [an issue](https://github.com/vimwiki/vimwiki/issues/217) earlier because I thought something was broken but then I noticed that it's explicitly listed as unsupported in the help files (see my same issue, one comment down. "only Vimwiki's default markup will be converted to HTML ")

If you _are_ getting HTML files out of markdown, but they're somehow screwy then you're experiencing something different than I. In poking around this repo a little I found a comment from someone who created a gem to address this: https://github.com/vimwiki/vimwiki/issues/57#issuecomment-94123419  
I haven't tried it out yet myself, but it seems promising.

**Comment by AdamKing0126** [comment]
You know what, I think this is a case of RTFM.  I didn’t realize that :VimwikiAll2HTML wasn’t compiling to markdown.  I’ll follow the syntax provided with the help file.

Thanks for your time and your patience.

Adam

**Comment by patrickdavey** [comment]
@AdamKing0126 I did create a [small rubygem](https://github.com/patrickdavey/vimwiki_markdown) that you can use to have markdown with vimwiki. There are probably some rough edges, but it has been working fine for me for a few years..

Also, can this issue be closed?
