### ISSUE TITLE
How to target .wiki ?

### ISSUE THREAD

**Issue by damionvega** [vimwiki/vimwiki#218]
I'm trying to set the text width of all my .wiki files to 80, the following has no effect:

```viml
au BufNewFile,BufReadPost *.wiki setlocal so=999 tw=80
```

**Comment by EinfachToll** [comment]
Does it help if you set `let g:vimwiki_table_auto_fmt=0` in your .vimrc? When it is activated, 'tw' is set to 0 when entering insert mode, but it normally is reset when leaving it.
That's the only place where Vimwiki is messing with 'tw'. Is there another plugin interfering? You can type `:verbose set tw` to see which script last changed the value.

**Comment by damionvega** [comment]
That didn't work. Here's the weird thing: `:verbose set tw` gives me the following:

```
  textwidth=80
        Last set from ~/.config/nvim/init.vim
```

**Comment by EinfachToll** [comment]
Well, there you have it. Check what `init.vim` does with `tw`.

> :set tw=80 in a new wiki does nothing either.

So you type that command, but the value of `tw` doesn't change? Then obviously something is wrong with your (Neo)vim.

**Comment by damionvega** [comment]
init.vim is where I'm setting the code I opened the issue with

**Comment by EinfachToll** [comment]
Again, if you type the command `:set tw=80` and it doesn't set 'tw' to 80, then this is a bug in (Neo)vim. There is no way for me as plugin writer to detect that you're about to change the setting and reset it (or whatever).

**Comment by damionvega** [comment]
Again, if I enter `:set ft=markdown tw=80` it works as it should. I don't understand why you've closed the issue.

**Comment by EinfachToll** [comment]
But if you leave out the `ft=markdown`, the setting is without effect, or did I understand you wrong? And this is clearly a bug in Neovim. I could tinker around with Vimwiki for hours, but that would be fruitless if your editor is messing things up. You should work out the minimal steps to reproduce the bug and file an issue to the Neovim project (assuming you're using Neovim and the issue is only present in Neovim, not Vim).
If this is fixed and your editor works properly and the original bug is still present, you can reopen this issue, of course.
