### ISSUE TITLE
URL shortening / concealing

### ISSUE THREAD

**Issue by Kinmarui** [vimwiki/vimwiki#312]
Hi,
I found this topic from more than year ago which describes my problem:
https://github.com/douglasdrumond/vimwiki/issues/402

I didn't find it on GitHub issue list and I think it is at least partially fixable see http://stackoverflow.com/a/3855499/1678568

I know it can be slow for big files but should work fine for smaller ones and would greatly improve user experience.

Great work & Best Regards,
Kinmarui

**Comment by EinfachToll** [comment]
I'm not sure I understand what your problem is. You can turn off the link shortening with this line in your .vimrc: `let g:vimwiki_url_maxsave=0`.

**Comment by Kinmarui** [comment]
But I love link shortening and when I have text wrapping and URL spans for 3 lines it would be great from readability point to be able to hide it. And currently I encounter same problem as described in provided link. I see empty lines when whole link could be shortened and I should see only description in one line.

On side note maybe I can circumvent this problem by writing vim plug-in that will use i.e. bit.ly to replace long links with shorter aliases.

**Comment by EinfachToll** [comment]
Maybe a solution is to use markdown syntax and reference-style links, so you can put the long URLs at the end of the file where you don't see them so often.
Anyway, I don't think there is something I can do on Vimwiki's side.

**Comment by paulsammut** [comment]
Grrrrrr I've also been struggling with this silly issue of the way the default vimwiki syntax handles URLs. The issue with me is that I use the html generator which is not available for markdown. If it was, i would just convert all the notes to markdown. It would be awesome if there was reference style URLs in vimwiki sytnax as there is in markdown

**Comment by l00sed** [comment]
I know this is an old thread... I don't even know if the issue you're describing is the same as what I've been experiencing. Basically all URLs were hidden in `.md` files and I couldn't see what I was editing. It was extremely frustrating. I was also getting a bunch of blank characters (presumably the invisible, shortened, URL).
I found the culprit was a vim plugin: 'Yggdroot/indentline' that was conflicting with either vimwiki or the vim-markdown plugin and overriding it (preventing the folded markdown syntax from being revealed when the cursor was pointed to the text). I removed the plugin and now all markdown files unfold as expected when the cursor is inside the text area.
Hope this helps someone!

**Comment by H3mul** [comment]
Thanks @l00sed! Your keen eye helped me find a solution. I was in the same boat, but wasn't ready to lose something as useful as indentline, here's how to make it work with vimwiki:

```
let g:indentLine_concealcursor=""
let g:indentLine_conceallevel=2
```
source:
https://github.com/Yggdroot/indentLine/issues/303

**Comment by l00sed** [comment]
Hey! Wasn't expecting this thread to be revived. Thanks for taking the time to share the fix. Excited to have indentline back!
Thanks @H3mul
