### ISSUE TITLE
Abstract syntax tree

### ISSUE THREAD

**Issue by ycpei** [vimwiki/vimwiki#314]
I found the following at the beginning of `html.vim`:

```
" TODO: We need vimwiki abstract syntax tree. If properly designed it wourld
" greatly symplify different syntax to HTML generation.
" 
" vimwiki   --            --> PDF 
"             \          /
" markdown  -----> AST -----> HTML
"             /          \
" mediawiki --            --> Latex
"
```

But I can't find any other information or discussion regarding this TODO. What is the status of this issue, and what can be the first step to take to implement an AST? Is it better to [implement it in Pandoc](https://github.com/jgm/pandoc/issues/863) instead?

**Comment by EinfachToll** [comment]
Hm. As you probably can see from skimming the rest of `html.vim`, the current status of the HTML converter is an unsystematic and ad-hoc approach which doesn't really use an AST.

Some time ago I reimplemented it using a parser generator (see https://github.com/vimwiki/vimwiki/issues/7), which in theory could be made to output LaTeX more easily than the old approach. But I rejected it in the end because
- it was slower
- thinking of a formal grammar for Vimwiki's syntax is complicated (AFAIK, the creator of Pandoc too said that these markdown-like syntaxes are not really easy to describe with a (kind of) context-free grammar)
- it's a bit of a pain to work with data structures in Vimscript

So my take is that if such a converter is made, it's not made in Vimscript, but with an external program. Pandoc looks indeed promising. It's only that somebody has to do it. Maybe me, but at the moment I don't even have as much time as I want to fix the regular bugs in Vimwiki :/

**Comment by ycpei** [comment]
Thanks for answering. I'm going to try writing a Pandoc reader for Vimwiki.

**Comment by ycpei** [comment]
Does the Vimwiki syntax have a Backus–Naur form?

**Comment by ycpei** [comment]
I have written a [Vimwiki reader for pandoc](https://github.com/jgm/pandoc/pull/3705). Closing this issue :)

**Comment by Nudin** [comment]
> I have written a Vimwiki reader for pandoc.

You stole me my project idea for my semester project… Or at least one of them. ;)

**Comment by ycpei** [comment]
@Nudin It was simply irresistable to try it out ;) By the way feel free to @ me if you encounter any problems using the Pandoc reader.
