### ISSUE TITLE
How to use "local"？

### ISSUE THREAD

**Issue by unix2012** [vimwiki/vimwiki#336]
**1.config。**
`let g:vimwiki_list = [{'path': 'E:/web/hussar/wiki',
\ 'path_html': 'E:/web/hussar/html/',
\ 'template_path': 'E:/web/hussar/template/',
\ 'template_default': 'template',
\ 'template_ext': '.html'}]`
**2.code**
`{{local:../html/image/aa.jpg|00001|style="width:160px,height:120px"}}`
**3.html**
`<img src="../E:/web/hussar/html/image/aa.jpg" alt="00001" style="width:160px,height:120px" />`
**4.problem**
How to use "local"？

**???**
‘E:/web/hussar/’

**Comment by ranebrown** [comment]
@unix2012 If you still need help please provided a detailed description of what you are trying to do and the expected behavior and what behavior you are actually seeing. Include all the information requested in the [issue template](https://github.com/vimwiki/vimwiki/blob/master/.github/issue_template.md).
