### ISSUE TITLE
Are typefaces restricted to single line?

### ISSUE THREAD

**Issue by sdothum** [vimwiki/vimwiki#340]
Typefaces (italic and bold emphasis) don't appear to be able to span lines where phrases are broken up with hard breaks (versus soft wrapping).

Is this an intentional restriction? (other markdown plugins seem to handle typeface emphasis across multiple lines)

**Comment by EinfachToll** [comment]
It's certainly true that the type faces can't span multiple lines. It's not easy to change that, though, because the HTMLizer works very much line based.

**Comment by bergercookie** [comment]
That would be really useful to have!
Any idea what sort of changes would be needed, and to what component to make this work?

**Comment by tinmarino** [comment]
__Syntax highlithing:__ are defined as `Vimwiki` bold in the [syntax files](https://github.com/vimwiki/vimwiki/blob/66a294d76f79efd52fbcda86d2238577b4253aad/syntax/vimwiki.vim#L382-L383) and its regex is defined according to the filetype [here for markdown](https://github.com/vimwiki/vimwiki/blob/dev/syntax/vimwiki_markdown.vim#L17-L22)

__Html convertion:__ For wiki syntax, the vimwiki script is using the highlight groups [there](https://github.com/vimwiki/vimwiki/blob/66a294d76f79efd52fbcda86d2238577b4253aad/autoload/vimwiki/html.vim#L613)

But there is not html convertion support for markdown: to annoying to code when pandoc is just perfect.
So you can start by making a pull request for markdown syntax. Which syntax, OS do you use @bergercookie ?

**Comment by galambborong** [comment]
I'm just seconding @bergercookie in agreeing that this would be a useful feature. In my case, I'm using commands as examples within body text using the code typeface, but it does not like the line breaks.

**Comment by tinmarino** [comment]
@galambborong It is actually fixed in tje dev branch, after a commit transforming syntax: match -> region.

I did this commit copiing $VIMRUNTIME/syntax : methodologie for nested region from html.vim and regex of delimiters fron markdown.vim as proposed above and forgot to report in this issue.

Cheers,
PS: I also like this feature

**Comment by galambborong** [comment]
Thanks for clarifying that @tinmarino - will check it out.

**Comment by bergercookie** [comment]
Just tested it and it's perfect! :) 
Thanks @tinmarino

**Comment by bergercookie** [comment]
One thing that I noticed after pulling the latest `dev` branch, is that now if I have a punctuation point e.g., a comma after the trailing `*`, it disregards the trailing `*` and colors everything until the end of the line in bold.

For example here's some sample text:

![2020-08-13-08:18:05-screenshot](https://user-images.githubusercontent.com/5816719/90096976-c31d5380-dd2c-11ea-9e3c-8fa129c9dc78.png)

I'll put the first part of the first sentence (until the first comma) in `*`s. Here's the text again (no filetype selected so that the highlighting doesn't kick in.

![2020-08-13-08:16:38-screenshot](https://user-images.githubusercontent.com/5816719/90097031-e7793000-dd2c-11ea-9e7c-839e485b2afe.png)

And here's how vimwiki now colors the text:

![2020-08-13-08:16:27-screenshot](https://user-images.githubusercontent.com/5816719/90097051-f4961f00-dd2c-11ea-880d-879af957adc8.png)
