### ISSUE TITLE
Link creating with single quote fails

### ISSUE THREAD

**Issue by breneser** [vimwiki/vimwiki#394]
Hi, when I press enter on a chapter title with single quote (') to create a link I get following error:

> 
> Error detected while processing function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>197_normalize_link_syntax_v:
> line   11:
> E15: Invalid expression: 'Sprucing Up Your Site's Navigation'
> Error detected while processing function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link:
> line    8:
> E171: Missing :endif
> Error detected while processing function vimwiki#base#normalize_link:
> line    3:
> E171: Missing :endif
>

**Comment by johnmarcampbell** [comment]
@breneser I wasn't able to reproduce this problem. Furthermore, the phrase 'Sprucing Up Your Site's Navigation' doesn't appear anywhere in vimwiki's source code.
1) Are you using the latest version?
2) If so, could you provide a concrete example that triggers this error?

**Comment by breneser** [comment]
@johnmarcampbell It has been a while I will check if I have the latest version and if this is still the case.

That phrase is not in the source code, just some notes I have been taking with Vimwiki :)

**Comment by johnmarcampbell** [comment]
Ahh, I see. I thought that phrase was somehow part of the internal error message. I see now that it's probably the text you were trying to make a link out of. Thanks for clarifying.

**Comment by EinfachToll** [comment]
I can reproduce this error: just type the text `foo'bar` into a Vimwiki file, select it in visual mode and press enter. The problem is that in autoload/vimwiki/base.vim in the function s:normalize_link_syntax_v(), the `@"` (which is a special variable in Vimscript which holds the content of the `"` register) needs to be escaped properly. Currently, if it contains a `'`, the concatenation blows up.
(^- Hint for my fellow developers ;)

**Comment by johnmarcampbell** [comment]
Okay, that makes sense. I'm able to reproduce the problem now. (I'm honestly not sure why I couldn't before :man_shrugging:). I'll take a look at it and see if I can't fix it.
