### ISSUE TITLE
Please make this plugin work with vim-markdown and vim-table-mode.

### ISSUE THREAD

**Issue by cstsunfu** [vimwiki/vimwiki#399]
Vim-markdown is powerful in write markdown. And vim-table-mode is a plugin which can calculate the table as org-mode. If you could fix it . Vimwiki is all most like org-mode except the schedule and calendar.   
I love org-mode and vim. I don't want to give up one of them. And the vimwiki is the most wonderful plugin in vim. So I write the issue.     I am sorry for my poor English, and thank you for your work.

**Comment by johnmarcampbell** [comment]
What changes do you think could be made? Are vimwiki, and vim-markdown currently incompatible? Or vimwiki and vim-table-mode?

Are there features in vim-markdown or vim-table-mode you think vimwiki should take advantage of? What are they?

**Comment by johnmarcampbell** [comment]
We've gone 7 days without getting additional info on this feature request, so I'm closing. We can reopen when this info is provided.

**Comment by jeaye** [comment]
I would love support for https://github.com/plasticboy/vim-markdown as well. In short, vimwiki's markdown syntax is lacking, compared to vim-markdown. The concealing, the highlighting, folding, and syntax regions for fenced off code are sorely missed.

Rather than vimwiki doing its own markdown thing, why not integrate vim-markdown?
