### ISSUE TITLE
Please appoint more maintainers. / Somone fork and take over maintaince?

### ISSUE THREAD

**Issue by dpc** [vimwiki/vimwiki#402]
Hi,

I really enjoy using vimwiki, but the fact that there is so many unhandled PRs is worrying me.

As a person that does open source projects in my free time, I am fully aware how hard it is to keep maintaining them. This project is very successful and popular, and it must take a lot of effort.

I don't know what's the current situation, but I'd advise the author(s) to pick a couple of users that submitted multiple PRs already and give them write access to the repo. While it might be scary to lose the total control over the project, it ensures project continuity and growth.

**Comment by EinfachToll** [comment]
I agree. Personally, I'm still strongly interested in keeping this project going, but my contributions will only be intermittent in the future. (Also, I feel a little overwhelmed when I see the bug list.)
So, any volunteers here who feel like not only adding their favorite features to Vimwiki but who also want to take a bit more responsibility and contribute regularly? Send in your applications now! ;)

**Comment by Nudin** [comment]
I would volunteer. I do admit, that I'm still relative new to vimscript and the vimwiki-code. But I want to continue learning and contributing and I hope that I can be involved regularly and long-term.
At least in the beginning I would only merge smaller/easier PR and leave the hard ones to you.

Also, I would propose having a chat about vimwiki. Maybe an IRC-Chat? I just joined #vimwiki on freenode – I will idle there, if someone is interested…

**Comment by dpc** [comment]
About IRC: Please make it gitter/matrix so it has a history. :)

**Comment by johnmarcampbell** [comment]
I volunteer. Similar to @Nudin, I'm still pretty new to vimscript. But I've just started to use vimiwiki pretty heavily a few weeks ago and really like it. So I'd enjoy an opportunity to get more hands on with the code. I could at least go through some PR's and do some light testing, etc. 

In addition to unresolved PRs, there are a lot of open issues that can probably be closed. For instance, when a user asks for help on a topic, receives it, and then leaves without closing the issue ([example here)](https://github.com/vimwiki/vimwiki/issues/397). I'd be happy to go through and find these and close them. Or, if we didn't want to grant me Maintainer rights off the bat, I could compile a list and give that to whoever has that ability.

**Comment by EinfachToll** [comment]
@Nudin and @johnmarcampbell I added you as collaborators for this repo. Feel free to pick a task according to your skills. Over the next days, I will go through the bug list and maybe label some of them as entry-level bugs etc. Please refrain from starting larger features until #256 is done, because this is a major blocker, but I'll try to work on it.

If you have questions, don't hesitate to ask here or in above IRC channel, where I probably will hang out in the evening hours (Central European Time).

If you push something or merge a PR, always on the development branch.

**Comment by optik-aper** [comment]
@EinfachToll Might I suggest that, since the issues list is daunting, someone do some clean up on the existing open issues.  I've been browsing them and it seems like there are quite a few issues still open that have been addressed in some way (thought often not fully resolved).  A few examples: #24, #225, #216.

There's probably a good argument for keeping them open but since the number of issues has been rising I think it would be beneficial for everyone if these types of issues were closed and forgotten for now.

**Comment by johnmarcampbell** [comment]
This is being worked on. We've closed 14 issues in the past three days, many of which are ones that were still open but had been addressed. It takes a while to work through the list. 

Thank you for noticing [#24](https://github.com/vimwiki/vimwiki/issues/24) and [#216](https://github.com/vimwiki/vimwiki/issues/216); I've just closed them. [#225 ](https://github.com/vimwiki/vimwiki/issues/225) has an open PR that would need to be addressed before the issue can be closed. If you notice any more, feel free to comment 'Can this be closed?' in the individual issue.

**Comment by optik-aper** [comment]
@johnmarcampbell Thanks!  I'll do that.

**Comment by hackeryarn** [comment]
I have been heavily using vimwiki for last few weeks and want to keep this project going. I would love to help with the maintenance of this project!

**Comment by ranebrown** [comment]
@EinfachToll if you are still looking for contributors I should have some time to help out.

**Comment by Nudin** [comment]
I created a follow-up-issue for applying as maintainer. I'm closing this ticket for the new one.

@ranebrown @hackeryarn If you are still interessted in helping as a maintainer please comment on #624! Also see #625.
