### ISSUE TITLE
Multi-paragraph blockquote possible?

### ISSUE THREAD

**Issue by waxlamp** [vimwiki/vimwiki#422]
Hi! I've been using VimWiki in earnest now for a couple of weeks and I love it -- thank you!

One question: is it possible to have a multi-paragraph blockquote? When I place multiple paragraphs of text indented by four spaces, I get *separate* blockquote elements in the resulting HTML. However, other systems (Markdown Here, GitHub Markdown) allow multiple paragraphs to be encased in a single blockquote.

Thanks again!

**Comment by brennen** [comment]
I'd thought that maybe it would work to do one with leading spaces for the blank lines, like so:

```
    foo
    
    bar
    
    baz
```

...can confirm that this still produces multiple blockquotes.  I'm not aware of any workaround at this point.

**Comment by ranebrown** [comment]
I'm labeling this as an enhancement/feature request for now. @brennen I don't anticipate any of us getting to this anytime soon but if you want to open a PR that would be awesome.

**Comment by eltrufas** [comment]
Hey, I want to work on this feature, but I wanted to ask about behavior first. Should I:
* Simply merge any adjacent block quotes: The disadvantage here is it'll break existing documents and it would make cases where you actually want multiple block quotes tricky.
* Make sure the lines inbetween have at least 4 spaces. This is iffy because some people (such as me) have their editor set to trim trailing whitespace, which would break it on every write.
* Or introduce a new syntax, such as surrounding the entire text with `"""` (like python multiline strings) or allowing block quotes to be prefixed with `>` instead (email style).

**Comment by waxlamp** [comment]
>     * Or introduce a new syntax, such as surrounding the entire text with `"""` (like python multiline strings) or allowing block quotes to be prefixed with `>` instead (email style).

I like this idea. The email style syntax makes more sense to me. FWIW, this is how Markdown Here enables both single-line and multi-line blockquotes.

**Comment by tinmarino** [comment]
Fixed by @elturfas with his awesome PR #901

**Comment by waxlamp** [comment]
Awesome!! Thanks @eltrufas!
