### ISSUE TITLE
Formula block display in vim not working

### ISSUE THREAD

**Issue by E1k3** [vimwiki/vimwiki#428]
When I create an empty wiki page and add a formula using the `{{$\n ... \n}}$` block, superscripts, subscripts and other symbols are still only displayed as T^2 instead of T² until I add a `$` in a previous line of the same block.
Example:
```
{{$

T^2
}}$
```
is displayed just like you see it here, whereas this

```
{{$
$
T^2
}}$
```
is displayed as:

```
{{$

T²
}}$
```

`$T^2$` also just displays as `T^2` and not as `T²`.
In all cases where the `_` is visible, it is marked red.

**Comment by E1k3** [comment]
Can nobody reproduce this or does it just not matter?

**Comment by ranebrown** [comment]
@E1k3 I tested all of the math block cases you mentioned and the `T^2` renders as T&#178; in each case. It looks like highlighting in the math blocks is done using [tex.vim](https://github.com/vim/vim/blob/master/runtime/syntax/tex.vim) (see [these lines](https://github.com/vimwiki/vimwiki/blob/750b3171b321872c17b88237db12822fc3e8c264/autoload/vimwiki/base.vim#L1037-L1048)). The inline math using `$ T^2 $` does not display as T&#178; but I didn't really dig into if that is by design.

This could be related to the font you are using not supporting the necessary characters.

There is some related info in #236.

**Comment by ranebrown** [comment]
This also is dependent on the `conceallevel` being set correctly.
