### ISSUE TITLE
mapping of VimwikiIncreaseLvlSingleItem to >>

### ISSUE THREAD

**Issue by joaocortes** [vimwiki/vimwiki#434]
Hi,
I've followed the sugestion  an put this maps on ~/.vim/after/ftplugin/vimwiki.vim:                      

 :map >> <Plug>VimwikiIncreaseLvlSingleItem
 :map >>> <Plug>VimwikiIncreaseLvlWholeItem

When I am using vim and want to quickly write something on my main wiki, I use <Leader>wt. However, after editing the wiki and closing, >> seems to remember the map that should be only used on wiki files.
That is, the mapping of >> to VimwikiIncreaseLvlSingleItem overrides the usual mapping, even on files without the wiki extension.

Is there a way to prevent this to happen?

Thanks

**Comment by ranebrown** [comment]
@joaocortes What is your expected behavior for `>>`? The default behavior is `>>			Shift [count] lines one 'shiftwidth' rightwards.` which is pretty much the same as increasing the list level (see `:h >>`) Try using a different mapping like `map nn VimwikiIncreaseLvlSingleItem` and test if that persists to a different file.

Please reopen if you are still having problems.
