### ISSUE TITLE
Please make it clear in the documentation which features require the dev branch

### ISSUE THREAD

**Issue by mrbig033** [vimwiki/vimwiki#503]
I spent a few hours trying to make some functions work, without realizing they are part of the dev branch. [vim-plug](https://github.com/junegunn/vim-plug) defaults to the 2.3 version, and there's no indication that such differences exist. I'd like to suggest these differences are clearly indicated in the documentation and in the readme. To be more precise, those features don't exist in the version I had:
* [<Plug>VimwikiIncreaseLvlSingleItem](https://github.com/vimwiki/vimwiki/blob/966a94bd477f3b10ae7b66693508274c9aaf1288/doc/vimwiki.txt#L399)
* [vimwiki-text-objects](https://github.com/vimwiki/vimwiki/blob/966a94bd477f3b10ae7b66693508274c9aaf1288/doc/vimwiki.txt#L610)

**Comment by Nudin** [comment]
You're not the first to run into this kind of problem. There are three things coming together that lead to a bad user-experience for vim-plug users:

- The last release of vimwiki is very old (Mar 2016), a lot has changed since than!
- The `master`-branch is (currently) abandoned, all development happens in the `dev` branch. (Which it therefore configured to be the default branch)
- Vim-Plug does not use the default-branch but uses the `master`-branch by default.

In the past I therefore already noted instructions to use the dev-branch on the website, I now also [added](7ad365e142e) this to the README. This does not solve but hopefully alleviates the problem.

I created two tickets proposing to release a new version (#504) and to consider using the master-branch again (#505).

**Comment by Nudin** [comment]
Master is now up2date again, new version comming soon → Closing this.
