### ISSUE TITLE
Consider switching back to the master-branch

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#505]
We should think about if it would be possible to switch back to the master-branch or update it regularly. 

Background:
- The `master`-branch is (currently) abandoned, all development happens in the `dev` branch. (Which it therefore configured to be the default branch)
- Vim-Plug does not use the default-branch but uses the `master`-branch by default. This leads to vim-plug users often using very old versions of vimwiki.

An alternative option could for example be to have somewhat regularly new releases and to have the version of the latest release always in the master-version.

**Comment by EinfachToll** [comment]
I think the distiction between master and dev is good. We have no automatic tests whatsoever (yeah, I have plans to change that, but that will take a lot of time) and because users have a bazillion of different Vim setups which at least I can't always keep in mind, we kind of need the brave dev branch users who test for us. But yes, I think we should merge and release more often in the future. I still wouldn't make master the default branch, simply because we had it like this in the past and users who make PRs would start off the master branch all the time, even though the doc says they shouldn't.

**Comment by Nudin** [comment]
Yes, I agree that it's good to have a distinction between a stable and a development branch. But they shouldn't diverge that strongly and we should think about which of both versions we "advertise" to the users since now defacto its chosen by there installation-method. While vundle uses the branch that is set as default on git, vim-plug uses the master-branch (in both cases: if not told otherwise), etc. People are not aware of that.

**Comment by EinfachToll** [comment]
You're right. Also, the default branch is what is shown to the user here on Github.
