### ISSUE TITLE
Markdown as wiki file

### ISSUE THREAD

**Issue by ghost** [vimwiki/vimwiki#517]
.vimrc
```
let g:vimwiki_global_ext=0
let g:vimwiki_list = [{'path': 'C:\Users\phtu\vimwiki',
                     \ 'syntax': 'markdown', 'ext': '.md'}]
```

`<leader>ww` create new file called `index.md` in `C:\Users\phtu\vimwiki`. So I suppose `path` is correct.
But `:set ft?` of `index.md` file always set to `vimwiki` (`filetype=vimwiki`). I don't know what settings were wrong!?

vimwiki in /opt instead of /start
Another question: How I convert `.md` files to htmls?

**Comment by dfinninger** [comment]
`let g:vimwiki_global_ext=0` is going to turn off _global_ vimwiki settings. You'll still have the vimwiki filetype inside of your wikis. (Empirically speaking, I'm not familiar with the code)

As for markdown -> HTML, [Pandoc](https://pandoc.org/) has a vimwiki input. Here's an [example blogpost](https://jamesbvaughan.com/markdown-pandoc-notes/) where someone made a makefile that converts their wiki to HTML.

**Comment by gisikw** [comment]
Looks like vimwiki forcibly sets the filetype both when setting up a new wiki buffer, and when entering a wiki buffer, with no explicit way to override this. And, in fact, if you do explicitly override it, it seems to break some keybindings (at least, backspace stopped working for me).

However, you can hook into the FileType event to change the syntax without breaking functionality, it seems:
`autocmd FileType vimwiki set syntax=markdown`

**Comment by yangmillstheory** [comment]
What's the point of having the `syntax` key in `g:vimwiki_list` if the `filetype` (and `syntax`) is always set to `vimwiki`?

**Comment by ranebrown** [comment]
The syntax option determines how things like links are created `[[page|description]]` vs `[description](page)` and how headers are display `= Header =` vs `# Header`. As for converting files to html when using markdown syntax - that isn't officially supported yet. There are a couple different ways to do this manually though.

You might be interested in #461 and #578

It doesn't look like there is an actual issue here, just a misunderstanding so I'm closing this. Feel free to reopen if you don't think this answers your question.
