### ISSUE TITLE
VimwikiRenameLink renames files but not links to it when using markdown reference-style links

### ISSUE THREAD

**Issue by molok** [vimwiki/vimwiki#52]
I created a page "antani", I tried renaming it to "foobar" but when the page was references like this
[antani][]

or this:
[Something][antani]

links were left untouched.

I thinks the bug lies in the function update_wiki_links_dir in the file vimwiki/autoload/vimwiki/base.vim because the regex it generates only works for vimwiki_WikiLinkTemplate1 or vimwiki_WikiLinkTemplate2

**Comment by tenllado** [comment]
This issue is closed, but it is still happening for me. I tested both on the master and the development branches.

A simple example would be:

Direcotry

[Linink to file Note1](Note1)

edit Note1, <leader>wr , change the name to Note1b

The link still shows as 

[Linink to file Note1](Note1)

This is not happening with original vimwiki syntax links, that can also be used in the markdown files inside vimwiki, but those are useless if I want to convert the file from markdown to html or whatever other format.
