### ISSUE TITLE
Vimwiki Error: Wiki 2 is not registered in your Vimwiki settings!

### ISSUE THREAD

**Issue by Shaedil** [vimwiki/vimwiki#537]
Hi, 
I want to create separate vim wikis for different areas of study.
So that it is cleaner and better to manage.

I've tried using the command: `2<leader>ww` However, it gives me the error 'Vimwiki Error: Wiki 2 is not registered in your Vimwiki settings!'

Where can I find the Vimwiki settings and how do I change them accordingly?
And yes, I've looked at #440, but their solutions do not work

![vimwiki](https://user-images.githubusercontent.com/17773568/43239882-f4d68c4e-9061-11e8-84d9-d99c43a2c133.PNG)

**Comment by Nudin** [comment]
Vimwiki by default has only one wiki configured. If you want to have multiple wikis you have to configure them in your `vimrc`, so that vimwiki knows where to save / find which of your wikis.

Here is a default config with two wikis saved in the folders "~/.vimwiki/" and "~/.blog":
```
let g:vimwiki_list = [
      \ {
      \         'path': '~/.vimwiki/',
      \         'auto_toc': 1,
      \         'list_margin': 4
     \   },
      \ {
      \         'path': '~/.blog',
      \         'auto_toc': 1},
      \ ]
```
Note: Pathes in this example are Linux-pathes, if you have Windows add the full path in Windows format `C:\foo\bar\`.

All Options are optional. If you want to continue using the default wiki at it's default-path add an Wiki with empty Config `{}` as first wiki int the list. You'll find more info at `:h vimwiki-register-wiki`.

**Comment by Shaedil** [comment]
It works now. Thanks!
