### ISSUE TITLE
Add command to navigate up the wiki hierarchy

### ISSUE THREAD

**Issue by hollasch** [vimwiki/vimwiki#568]
I frequently want to navigate _up_ the wiki hierarchy in situations where this is different from going _back_.

I have a working prototype of this behavior, mapped to both ctrl-left and shift-up. (I'd love to use ctrl-up, but unfortunately that's already use to create a new diary directory.)

The prototype basically navigates to `<index>.<ext>` if the current page isn't an index. If it _is_ an index, then it determines if `../<index>.<ext>` exists, and edits that page. If that's not available, it prints a message that we're at the top of the current wiki.

If this sounds useful, let me know and I can create a pull request.

**Comment by hollasch** [comment]
After thinking about this more, I think the best mapping is shift-backspace, as an alternate to the currently mapped backspace. That is, <BS> goes to the prior page, and <S-BS> goes up the wiki hierarchy until it hits the root index page.

Should I create a pull request?

**Comment by EinfachToll** [comment]
Honestly, I find the use case you described a little weird. IMO, the great thing about a wiki in general is that you can link from any to any page without thinking about what is allowed here and what not. Links like `[[a/b]]` should be regarded more like name spaces to avoid name clashes instead of hierarchies. Sure, you can use them this way, if it works for you, but I wouldn't encourage the users to do so.

In my own wiki, I do have a kind of a hierarchy, but it is purely based on the links between pages (for example, my index page links to a page which only consists of links to various topic pages, e.g. a page "programming languages" which in turn contains only links to pages about specific programming languages).
