### ISSUE TITLE
vimwiki doesn't seem to use markdown syntax correctly

### ISSUE THREAD

**Issue by vikashiiitdm** [vimwiki/vimwiki#576]
hello, i've installed vimwiki and did some configuration in my .vimrc like this :
````
let wiki_1 = {}
let wiki_1.path = '~/vimwiki/'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.md'

let g:vimwiki_list = [wiki_1]
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
````

But, vimwiki doesn't seem to support markdown properly like asterisk bolds and underscore italicises. I only use markdown, and would like to know how to fix this?

**Comment by Nudin** [comment]
I can't reproduce that.
I tried the following .vimrc (with vimplug):
```
set nocompatible
filetype plugin indent on
syntax on

call plug#begin('~/.vim/plugged')
Plug 'vimwiki/vimwiki'
call plug#end()

" vimwiki
let wiki_1 = {}
let wiki_1.path = '~/vimwiki/'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.md'

let g:vimwiki_list = [wiki_1]
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}

```
and it work's like this:
![bildschirmfoto zu 2018-12-19 21-38-10](https://user-images.githubusercontent.com/509205/50246742-727a1980-03d6-11e9-8730-840c78148fa2.png)

**Comment by llinfeng** [comment]
@rpgormley, to answer your initial question, you need to specify the following for properly rendering the `*Bold*` and `_italicises_` markups. (I believe Vimwiki takes single `*` as the bold marker).

    setlocal conceallevel=2

I set this line in the `~/ftplugin/vimwiki.vim`, as I don't want to distort my other `conceallevel` settings elsewhere.

More on your `<CR>` (or Enter-key) problem: in short, I do not encouter such problem.

Longer version ==> I was not assuming `[[Page]]` syntax to continue working after switching to the markdown syntax (mostly according to @Nudin's demo settings above), but was outjoyed to discover that those `[[page]]` markers should continue to work. I did nothing fancy about the settings, and to summarize what I did, here goes the list of settings:
1. In `~/.vimrc`, specify the proper keys when initializing the wiki, namely the `syntax` key and the `ext` key.
2. More importanly, in `~/.vimrc`, specifying the `vimwiki_ext2syntax` variable appoints the proper syntax for Vimwiki to issue when dealing with files of `*.md` extensions. (Otherwise, pressing `=` in normal mode will add `= Headline =` instead of the proper Markdown syntax.)
3. Apply the proper conceal settings as mentioned above, to show/hide markers.

I have recently convert 2K files in `*.wiki` into `*.md` (failing for 150 or so of my early notes that contain special characters), and my impression is that all the Markdown businesses will be taken over by Vimwiki. An observation goes as the `filetype` for all `*.md` files will be `vimwiki`, as it appear to Vim.

**Comment by ranebrown** [comment]
See #318
