### ISSUE TITLE
visually reinforce headers without breaking toc

### ISSUE THREAD

**Issue by divramod** [vimwiki/vimwiki#618]
Hey, thx for this awesome plugin!
It is currently changing how i work ;-)

I like to visually reinforce the headers of documents a little bit more.
Is that somehow possible without destroying the table of contents which is created by ```VimwikiTOC```.
I really like that feature, but usually i am trying to visualize different areas in my documents with something like:

```
# Header 1 =======================================================

## Header 2 ----------------------------------------------------------------------------------------------

### Header 3 ..............................................................................................................
```

And that will make the toc unreadable.

Is that somehow possible to achive without breaking the TOC?

Thx again for the awesome plugin and in advance for possible hints to solve my problem!

**Comment by ranebrown** [comment]
Does it not work for you to place the visual reinforcement on the line below the header? I added a leading `\` since `-----` results in this behavior: "4 or more dashes at the start of the line is a horizontal line (`<hr />`)"

```text
# Header 1
\=======================================================

## Header 2
\----------------------------------------------------------------------------------------------

### Header 3
\..............................................................................................................
```

You might be interested in [setext style headers](https://spec.commonmark.org/0.17/#setext-headers) but that only supports H1 and H2. We have a couple of issues related to supporting this header style but no one has had a chance to implement it yet. (#272, #273, #209, #101)

**Comment by ranebrown** [comment]
@divramod I'm going to close this but feel free to reopen if you want to follow up.

**Comment by divramod** [comment]
i can use that, thx for the hint!
