### ISSUE TITLE
Version 2.5 Release

### ISSUE THREAD

**Issue by ranebrown** [vimwiki/vimwiki#638]
Issue to track the next release. I know v2.4 was just released but there have already been a large number of changes/fixes since then. Just want to get this on the roadmap. I created a [project](https://github.com/vimwiki/vimwiki/projects/2) if anyone is interested.

**Comment by ranebrown** [comment]
@Nudin what are your thoughts on doing a release? There are a lot of changes piled up on `dev` and I think it's time.

**Comment by artkpv** [comment]
Hi, thanks for developing this great tool! Waiting for the 2.5 release. Meanwhile, could we checkout and use 'dev' branch to test the changes? Or it is not in a running state?

**Comment by ranebrown** [comment]
The dev branch is generally pretty stable so feel free to use it. Take a look at the changelog in `doc/vimwiki.txt` for a list of features and fixes.

**Comment by Nudin** [comment]
I'm currently writing my thesis and therefore can't invest time into looking into the patches. I would therefore propose to plan to release 2.5 in mid-march. Is that fine for you?

**Comment by ranebrown** [comment]
That works. I definitely want to get a second set of eyes on everything. Good luck with the thesis!

**Comment by thecliguy** [comment]
@Nudin I'm almost reluctant to ask this question... Given what's going on in the world at the moment, this could either be a great time to do a release (people stuck at home with not much to do) or the worst possible time (people have bigger concerns occupying them right now). What are your thoughts on a doing a release?

**Comment by Nudin** [comment]
@thecliguy Yes, I would very much love to make a release. I just finished a release for one of my other project and will hopefully finish the mostly done release of yet another project in the next few days. After that I will devote time to vimwiki. I already started reviewing all the patches that came into `dev` since the last release – only 12 commits still to review. I will then take a look if anything other can/should be merged before releasing 2.5 and about how things are going on here in general.

**Comment by Nudin** [comment]
March is long gone and I finally managed to review all the work you all have done. It's great to see that there are quite a few new contributors and some people who repeatably contribute and maintain the project. Thanks to everyone, you're awesome!

So let's get 2.5 finished and released. Here are the last open questions I see:
 - [ ] 5126967d095e92c73c772e0e918554d378a43ef1:  Rename VimwikiGenerateTags → VimwikiGenerateTagLinks 
  I fully support renaming this command – but there is at least one (probably more) other command that does a different thing than what the name says. These changes are non-backward-compatible in the sense that some people might be irritated when a command is 'suddenly' missing. Should we:
   - [ ] Change them all at once, so that we don't annoy people by again-and-again renaming some commands in new versions?
   - [ ] Should we deprecate them and/or add a temporary warning? For example when using `VimwikiGenerateTags` in 2.5 it does its job but also shows you a warning that you should use `VimwikiGenerateTagLinks` instead. And only in 2.6 remove the alias.
- [ ] 3b5537f15aecbdf7ea66611e7d58b6aea96309ca: Link containing only '-'
  I would like to go the opposite way: When pressing Enter on a `-` nothing should happen. I had this on my todo-list for some time since I often accidentally do this (due to other mappings of `Enter`). I doubt that many people want to create a file `folder/-.wiki` or `folder/-.md` and for the hypothetical, rare cases they can still create them manually by writing the link themselves. I on the other side am pretty sure that I'm not the only one hitting it accidentally.
- [ ] 75c557bcbca7d9ebf461629e2818e7c21786e6f7: Commenting out unfinished code
  Did I get the reason for this commit right: we added a feature but then saw that it isn't finished yet since it has negative side effects? But it should be fixable, right? Is someone planing on doing this? In general, I would prefer us not to add commented-out code to the code base (we have quite a few of that, and I'm guilty of at least one of them!). That's what git branches are for. But let's leave this patch in there now.

Would love to hear your opinions on these points. Are there any other points you see that need to be addressed before releasing 2.5?

**Comment by brennen** [comment]
> 3b5537f: Link containing only '-'
> I would like to go the opposite way: When pressing Enter on a - nothing should happen. I had this on my todo-list for some time since I often accidentally do this (due to other mappings of Enter). I doubt that many people want to create a file folder/-.wiki or folder/-.md and for the hypothetical, rare cases they can still create them manually by writing the link themselves. I on the other side am pretty sure that I'm not the only one hitting it accidentally.

Yeah, one vote for the no-op behavior.

> Should we deprecate them and/or add a temporary warning? For example when using VimwikiGenerateTags in 2.5 it does its job but also shows you a warning that you should use VimwikiGenerateTagLinks instead. And only in 2.6 remove the alias.

I'd favor a deprecation period.  People may have scripted around existing commands, etc.

**Comment by tinmarino** [comment]
> 3b5537f: Link containing only '-'
I would like to go the opposite way

I also agree. Even if I am the one that coded that (bad) way.
I changed the behavior, nothing happens if url seems crappy (`s:clean_url` returns ''')
Fix: 9725948

**Comment by ubitux** [comment]
I'd go further and skip the `- ` (pos+2) and apply the make link on the list entry itself.

**Comment by Nudin** [comment]
I would suggest renaming and deprecate the following three commands:
- :VimwikiDeleteLink → :VimwikiDeletePage
- :VimwikiRenameLink → :VimwikiRenamePage
- :VimwikiGenerateTags → :VimwikiGenerateTagLinks (already renamed)
Calling the old command would work a previous but display a warning message.

Does anyone oppose? Otherwise, I'd implement that and after that start preparing the release. Any other ideas or comments?

**Comment by ranebrown** [comment]
I agree on the command renames. The commented code in 75c557b was my fault. It wasn't tested enough and didn't work as expected. I plan to work on it at some point.

**Comment by Nudin** [comment]
> I agree on the command renames. The commented code in [75c557b](https://github.com/vimwiki/vimwiki/commit/75c557bcbca7d9ebf461629e2818e7c21786e6f7) was my fault. It wasn't tested enough and didn't work as expected. I plan to work on it at some point.

Don't worry, I have several of these lying arround…

**Comment by Nudin** [comment]
After there were no further comments, I now released 2.5 – spread the word and hope for the best (no need for a 2.5.1)! Thanks and :heart: to everyone who contributed (the list got significantly larger!).

**Comment by Nudin** [comment]
I posted a note on HN, Lobsters and Reddit (pending approval):
- https://news.ycombinator.com/item?id=23316994
- https://lobste.rs/s/kc5a3g/vimwiki_2_5_personal_wiki_for_vim
- https://www.reddit.com/user/MSchoenitzer/draft/51fa386e-9f9f-11ea-9b42-42fb3966873d

**Comment by joshuavial** [comment]
Thank you for the new release, I've just started using vimwiki and was struggling with backlinks in markdown which the new release fixed. Appreciate all the work that has gone into the project.
