### ISSUE TITLE
Table formatting problems when setting filetype manually

### ISSUE THREAD

**Issue by mightymicha** [vimwiki/vimwiki#677]
Hi,

I'm using neomutt for writing mails in markdown and converting them to HTML prior to sending. 

For example `vim -c 'set filetype=vimwiki' test'
That way, I get vimwiki functionality within vim. 
But tables do not seem to work properly, because pressing <tab> or switching between normal / insert mode does not trigger table formatting, and thus the position after jumping will be wrong.

Tested on master and dev.

**Comment by hq6** [comment]
Please provide a sample file that exhibits the undesirable behavior.

**Comment by mightymicha** [comment]
Minimal vimrc
```vim
if &compatible
set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

" if dein#load_state('~/.vim/dein')
call dein#begin('~/.vim/dein')

call dein#add('~/.vim/dein/repos/github.com/Shougo/dein.vim')
if !has('nvim')
call dein#add('roxma/nvim-yarp')
call dein#add('roxma/vim-hug-neovim-rpc')
endif

call dein#add('vimwiki/vimwiki', {'rev':'dev'})

let g:vimwiki_list = [{'path':'~/documents/wiki2', 'syntax':'markdown', 'ext': '.md'}]

call dein#remote_plugins()
call dein#end()
call dein#save_state()
filetype plugin indent on
syntax enable
```

Steps to reproduce:
```bash
$ vim -c 'set filetype=vimwiki' test
```
Within file test:
```
:VimwikiTable<CR>
ji
<Tab>abcd<Tab>e<Tab>f<Tab>g<Tab>h<Esc>
```

Result:
```
| abcd  | e  | f  | g  | h  |
|---|---|---|---|---|
|   |   |   |   |   |
```

Notice how the autoformat between tabs or when switching between insert and command mod does not work. Reformatting afterwards with `gqq` does work.
Other features (e.g. lists) do work that way.

**Comment by ranebrown** [comment]
This is because the autocommands defined [here](https://github.com/vimwiki/vimwiki/blob/1e5c93ea917bbb27cade5de54fc120a989333f32/plugin/vimwiki.vim#L308-L338) require an extension `s:ext` and the autocommands are only defined for that extension. This is normally `*.wiki` but you can use the option `g:vimwiki_ext2syntax` to use any extension you like. For example, `let g:vimwiki_ext2syntax = {'.mail': 'markdown'}` will use the markdown syntax for any `*.mail` files and `vim -c 'set filetype=vimwiki' test.mail` should have all the Vimwiki functionality.

Does that work for you?

**Comment by mightymicha** [comment]
Neomutt creates a temp file with no specific extension when creating a new mail. When I come up with a solution tweaking either vimwiki or neomutt I will post it here. For now, I just live with `gqq`ing after every step. Luckily I do not need tables that often in emails :smile: 
Would be easier though, if it would only check the filetype or if there is a command which triggers that autocommands.
Thanks for your link.
Best 
Michael

**Comment by ranebrown** [comment]
You should be able to place something like this in your `.vimrc` to at least get the table formatting working. I think those functions would get called twice for a standard vimwiki file since two different autocommands would call it but I don't think that will cause problems. I'm sure there are other ways to get it working as well. Good luck!
```vim
augroup MailVimwiki
    autocmd Filetype vimwiki
        \ autocmd! MailVimwiki InsertLeave <buffer> call vimwiki#tbl#format(line("."), 2)
    autocmd Filetype vimwiki
        \ autocmd! MailVimwiki InsertEnter <buffer> call vimwiki#tbl#reset_tw(line("."))
augroup END
```
