### ISSUE TITLE
shift-enter and control-enter not working?

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#683]
Branch: dev
Revision: 2b6fa27
Date: 2019-04-22 07:39:11 -0700

The `shift-enter` and `control-enter` commands don't open the new file up in a split which I think is the expected behavior if I'm interpreting the documentation correctly. Instead, the link is just opened in a brand new buffer by itself.

My .vimrc:

```
syntax on
filetype plugin on
set nocompatible
set background=dark
set cindent
set tabstop=2
set shiftwidth=2
set expandtab
nnoremap sv :source $MYVIMRC<CR>

execute pathogen#infect()
execute pathogen#helptags()
```

I have removed all other plugins.

**Comment by sdondley** [comment]
I just read the help docs. It said it may not work in all terminals and to try remapping. I'm using iTerm2.

**Comment by hq6** [comment]
@sdondley, I think the problem is that many terminals capture these keybindings and try to interpret them, rather than passing them onto Vim. 
I use `gnome-terminal` and it has the same problem, but remapping seems to work fine. 
For example, I tried the following mapping in my `.vimrc` and it did the correct behavior.

```
nmap  <Leader>ws <Plug>VimwikiSplitLink
```

Please us know if that helps, but this is ultimately not a Vimwiki issue but rather a terminal issue. We could change the default mappings, but I do not know of any way to ensure that they work on all terminals.

**Comment by sdondley** [comment]
Yeah, I just did a remap. If you'd like, I can submit a patch to document this in the readme. May save people some frustration.

**Comment by sdondley** [comment]
I made a change to the changelog with a PR # of 683, this issue. This is actually PR #687, though. Not sure if I did things correctly. Please advise.
