### ISSUE TITLE
How to search by multiple tags?

### ISSUE THREAD

**Issue by shihabdider** [vimwiki/vimwiki#723]
How do you use :VimwikiSearchTags to search by multiple tags? e.g If I have the tags :programming:python:oop and I want to search on both :programming: and :python:, irrespective of order (i.e show me all files that have both those tags)

**Comment by matt-snider** [comment]
Hi @shihabdider 

I had the same question several months ago and found that it isn't possible. Vimwiki uses a [CTAGS](http://docs.ctags.io/en/latest/) file to store tag information, and I wasn't able to find _any_ tool that can query with multiple tags.

I wrote [vim-tagquery](https://github.com/matt-snider/vim-tagquery) for myself because I do these kinds of queries often. It works for my needs, but I don't know of anyone else using it so it might be a bit rough around the edges. If you are interested, try it out. If you run into any issues, please report them there.

**Comment by ranebrown** [comment]
I added a link to vim-tagquery in the [Vimwikiwik](https://vimwiki.github.io/vimwikiwiki/Related%20Tools.html).
