### ISSUE TITLE
automatic nested syntax highlighting not working for me

### ISSUE THREAD

**Issue by mdm508** [vimwiki/vimwiki#753]
I am not sure what I am doing wrong but for some reason automatic_nested_syntaxes higlighting feature is not working for me. Here are the vimwiki settings in my .vimrc 
```
" vim wiki settings 
set nocompatible 
filetype plugin on 
syntax on 
 let wiki = { } 
let wiki.template_default = 'default' 
let wiki.template_ext = '.html' 
let wiki.nested_syntaxes = {'python': 'python', 'bash': 'sh'} 
let g:vimwiki_list = [wiki] 

```

when I try  the following block inside of vim wiki nothing is highlighted.
```
{{{python
   for i in range(10):
       print("hello world")
}}}
```

Am i supposed to have included in the vimrc: 

`let wiki.automatic_nested_syntaxes = 0 `

**Comment by ratfactor** [comment]
I'd never tried that feature before. And at first, I didn't think it was working either.

Turns out, I needed to restart Vim and/or re-load my wiki page to see it!

Here's how it works (from what I can tell):

1. Any syntax specified in the `nested_syntaxes = { ... }` list is available immediately. (Don't forget to re-source the setup file or restart Vim.)  Any code blocks with that syntax will start highlighting immediately.
2. Without setting `nested_syntaxes`, VimWiki will _still_ automatically detect it when a wiki file containing a syntax-specific code block is _opened_.
3. You do not need to disable `automatic_nested_syntaxes` for the `nested_syntaxes` list to work.

The important thing is that you won't get any highlighting until the syntax has been loaded (via the `nested_syntaxes` list or by opening an _existing_ wiki page containing a code block with a specified syntax).

As an example, I typed a Tcl snippet into a wiki page and did not see any highlighting:

```
{{{tcl
set place world
puts "Hello $place"
}}}
```

Then I added a `'tcl': 'tcl'` entry to your syntax list, re-opened Vim and re-typed the snippet.  The highlighting showed up as soon as I'd typed `{{{tcl set...`.

Hopefully you just needed to restart Vim to pick up the setting?

**Comment by mdm508** [comment]
Thank you for your reply. I went back and followed the instructions you mentioned. Unfortunately, still not getting any highlighting even after reloading vim wiki page and sourcing vimcr. I wonder if I have some sort of problem with my settings in vimrc that are conflicting. 

[my_vimrc.txt](https://github.com/vimwiki/vimwiki/files/3714872/my_vimrc.txt)

**Comment by ratfactor** [comment]
Hmmm... yeah, I don't see anything that stands out as being problem in your `.vimrc`.

What happens if you manually set the filetype while viewing the wiki page containing your Python sample?

```
:set filetype=text
:set filetype=python
```

Does the highlighting change for the whole page as expected?

**Comment by mdm508** [comment]
yes highlighting changes for the whole page.

**Comment by ranebrown** [comment]
Maybe give the [minimal vimrc steps](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc) a try?

**Comment by mdm508** [comment]
> Maybe give the [minimal vimrc steps](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html#Troubleshooting-Minimal%20Vimrc) a try?

Thank you, I should have tried this to begin with. I got rid of the airline plugin as well as rainbow higlighting parens and removed some junk from the vimrc and that did the trick
