### ISSUE TITLE
Generated sections not compatible with older versions of Vim

### ISSUE THREAD

**Issue by ranebrown** [vimwiki/vimwiki#781]
PR #634, PR #635, and PR #636 introduced new features that broke compatibility with older version of Vim.

v7.4.1989 modified filter() to accept a Funcref
v7.4.2120 Added function "closure" argument
v7.4.2137 add funcref()

**Comment by tinmarino** [comment]
I tested your patch on `vim_7.4.1099`. It does not work (that's why you removed it maybe). I think this retro compatibility issue is a good initiative. What I noted so far :

1. E729: using Funcref as a String
2. VimwikiTOC not working on readonly or diff -> We should make a check earlier and return error : `echoerr "E21: Cannot make changes, 'modifiable' is off" | return` https://github.com/vimwiki/vimwiki/blob/c8bb65836047306cd9ce0f2704ce7fe439377e3c/autoload/vimwiki/base.vim#L1135-L1137
3. Error detected while processing function `vimwiki#base#table_of_contents[76]..vimwiki#base#update_listing_in_buffer:
line   86:`
E725: Calling dict function without Dictionary: 3
E15: Invalid expression: a:Generator()

The 3 means that it won't be that easy to refer to a parent variable.
I can care that if you like. Trying some stuff anyway.

**Comment by tinmarino** [comment]
# 2/2 A solution (not so dirty)

@ranebrown : I leave you the critic of my critic of your patch

I replace your dict container by script scoped variable (script container). Because some vim version cannot find the dict holder of the function. Hence the `E725` errormsg.

I pushed an updated version of command.vader. Before the patch 5/10 tests work, after 10/10 



### PS : The patch description :

```
5,7K  0001-Rane-vimWikiTOC-fix.patch
5,3K  0002-Retrocompatibility-before-v7.4.2137-make-variable-sc.patch
1,0K  0003-VimwikiTOC-check-if-diff-or-ro-and-return-echomsg.patch
1,1K  0004-Prettify-Generator-function-harmonize-names.patch
``` 

### PS2 : now I understand why you putted a `txt` extension

[retrocompatibility.txt](https://github.com/vimwiki/vimwiki/files/3919801/retrocompatibility.txt)

**Comment by ranebrown** [comment]
Sorry about the confusion with that other patch I added. I realized it wasn't quite there so I deleted it. I think these should be better. I won't have a chance to look at this anymore for a week so but I can take a look at your option then.

[01_patch.txt](https://github.com/vimwiki/vimwiki/files/3919860/01_patch.txt)
[02_patch.txt](https://github.com/vimwiki/vimwiki/files/3919861/02_patch.txt)

**Comment by ranebrown** [comment]
We should make sure to test `VimwikiTOC`, `VimwikiGenerateLinks`, `VimwikiGenerateTags` (make sure to `VimwikiRebuildTags` first) and `VimwikiDiaryGenerateLinks` to make sure this is all working correctly.

**Comment by ranebrown** [comment]
Seems like both patches are performing the same right now. I kinda like my version but that's probably because I spent a bit of time figuring out how to get the dictionary functions to work how I wanted ;)

**Comment by tinmarino** [comment]
Don't you get `E725: Calling dict function without Dictionary: 3` with `vim_7.4.1099` and your dict solution ?
That is why I worked on that on the first place. Your solution is elegant. But it seems (to me) that the dict is disappearing from the scope for early vim's version. Declaring the dict as global can solve that too.
In my opinion, on `vim_7.4.1099`, we need to leave the scope of the calling function `vimwiki#base#generate_links(create)`
