### ISSUE TITLE
Make g:vimwiki_list_markers a (per-wiki) option?

### ISSUE THREAD

**Issue by EinfachToll** [vimwiki/vimwiki#8]
Although I'm a fan of reasonable default settings, should we make g:vimwiki_list_markers an option, so that the user can specify which kind of marker he uses most often and in which order the markers appear when pressing `i_<c-l>k` and `i_<c-h>j`?
Another solution could be dropping this list and map `i_<c-l>*, i_<c-l>-, i_<c-l>A` etc., analogously to `gl*, gl-, glA` etc.
At the moment it's a bit cumbersome to type a long list where the child items usually have a different marker than the parents, because on every `<c-t>` you have to change the marker manually again. I'm thinking of a method to determine the desired marker automatically from what the user has chosen the last time. But this is where things get complicated, I suspect. :)

**Comment by mMontu** [comment]
I know this issue is kind of old, but I thought I could comment here as it is still relevant.

I like the current behavior for `i_<c-t>` when the item already has child items: the plugin copies the style from the existing childs.
But I agree with EinfachToll that it is a little cumbersome to manually change the style of the first child in order to make it different from the parents.

Even without customizing the order of the markers I think it would be nice if the first child always cycled to the next marker style instead of just copying it from its parents.

**Comment by ranebrown** [comment]
From the lack of activity on this I think people have been happy with the current behavior. This can always be reopened if there is renewed interest.
