### ISSUE TITLE
`:VimwikiGenerateLinks` for subdirectory only?

### ISSUE THREAD

**Issue by beuerle** [vimwiki/vimwiki#803]
- branch: `dev`
- revision: `d94122`
- syntax: markdown

Running `:VimwikiGenerateLinks` currently produces a list of links to **all** wiki files relative to the location of the file the command is run from.

Did I miss something in the documentation and it is possible to run `:VimwikiGenerateLinks` to only produce a list of links to files in the current directory?

----

Example:

- wiki structure

```
vimwiki/
    README.md
    lorumipsum.md
    dir/
        README.md
        lorum.md
        ipsum.md
```

- current output when running `:VimwikiGenerateLinks` in `vimwiki/dir/README.md`

```markdown
# Generated Links

- [README](../README.md)
- [lorumipsum](../lorumipsum.md)
- [README](README.md)
- [ipsum](ipsum.md)
- [lorum](lorum.md)
```

- similar to `:VimwikiGenerateTags`, `:VimwikiGenerateLinks` could take an argument to create a list of links valid just for the current directory, the output in `vimwiki/dir/README.md` would then look like

```markdown
# Generated Links

- [README](README.md)
- [ipsum](ipsum.md)
- [lorum](lorum.md)
```

**Comment by ranebrown** [comment]
I don't think it is possible currently but it could be a useful addition. If you are interested in creating a PR that would be the best way to get the feature added.

**Comment by tinmarino** [comment]
@beuerle very nice feature idea.
I like easy wins: I'll code it soon but if you want it: it is your idea: I can leave it to you.
2h work.

**Comment by tinmarino** [comment]
Feature added: f4c983b6b5332
Rebase on dev and
```vim
:VimwikiGenerateLinks *.md
```
`:h globpath` to see the pattern format

**Comment by Whyglobaleyes** [comment]
Hello,
@tinmarino I really appreciate this feature because I'm migrating from a very longstanding zimwiki with a carefully curated folder structure and using your globpath method I can create a TOC page with the correct scope. Thank you. 

Anyone ... 
I'd like to have a quick way to insert a TOC with all the notes in whichever folder I'm in - I want to set a keybinding so that it's easy to create the TOC for the current directory ... so do you know if there's a syntax I could use to specify the current directory please? 
- I took a guess and tried ``` :VimwikiGenerateLinks ${PWD}/*  ``` + several variations which failed
- I tried ``` :VimwikiGenerateLinks $CWD/* ``` and that outputted a list of all the files/ directories in my ``` ~/vimwiki ``` even though I was in ``` ~/vimwiki/lifeDomain/domainArea/projectName/0_projectName_index.md ``` :: that makes sense because ~vimwiki was the CWD when I launched vim so I guess what I'm aiming for is to be able to specify the CWD of the active buffer. Too recent a vim-convert to know if that's do-able.

Possible or not?

**Comment by Whyglobaleyes** [comment]
Just in case this helps anyone in future trying to achieve the same thing ... I think I've figured out a work-around. I don't really understand it all so would appreciate any improvement suggestions please ... 

1. `expand("%:h")."/*"` returns the directory of the current buffer with a slash/wildcard at the end.
2. for some reason _**(please can anyone explain why or show me the correct syntax?)**_ I can't get the expansion to work in the command line, I tried several variations of: `  :[execute] VimwikiGenerateLinks [expand]("%:h")."/*"  `
3. However it worked when I set up a function in .vimrc:
```
function g:LocalIndex()
  let route=expand("%:h")."/*"
  execute "VimwikiGenerateLinks" . " " . route 
endfun
```
4. extra convenience: (a) adhere to a naming rule for index pages and (b) add the following line to .vimrc:
```
let g:auto_generate_links=1
autocmd BufEnter *MyIndex.md :call LocalIndex()
```

OUTCOME: In any subdirectory an auto-updating index page (that only lists the files in that subdirectory) can be created by touching a page called "randomtextMyIndex.md" in that subdirectory.

---

relates to:
https://github.com/vimwiki/vimwiki/issues/983
https://github.com/vimwiki/vimwiki/issues/1207
