### ISSUE TITLE
Unexpected visual mode markdown link generation behavior

### ISSUE THREAD

**Issue by sharingtom** [vimwiki/vimwiki#909]
- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
```
let wiki = {}
let wiki.path = '~/brain/wiki'
let wiki.path_html = '~/brain/wiki_html'
let wiki.syntax = 'markdown'
let wiki.ext = '.md'
let g:vimwiki_list = [wiki]
```
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

**Example 1**

Start with the following line:

```
Test
```
In Normal mode, press Shift-v and then Enter.

Expected outcome:
```
[Test](Test)
```
Actual outcome:
```
[Test](Test
)
```

**Example 2**

Start with the following line:

```
Test Test
```
In Normal mode, with the cursor at the beginning of the line press v w Enter.

Expected outcome:
```
[Test](Test) Test
```
Actual outcome:
``` 
[Test T](Test T)est
```

- [x] Include the output of `:VimwikiShowVersion`.
```
Os: Linux
Vim: 801
Branch: dev
Revision: a9f21c6
Date: 2020-06-08 14:31:35 +0200
```
(Have tested 2.5 as well.)

**Comment by tinmarino** [comment]
Nice description. I can reproduce it. It is the expected behavior. So I'll consider it as a question

### 0 Input:
```text
Test Test
```
### 1 Shift V
__Shift-V__ is selecting the trailing newline. Which is usually usefull when copy-pasting some lines. You will often experience the same issue interacting with the system clipboard.
`<S-V><Cr>` will select "__Test Test\<Nl\>__" where \<Nl\> is a new line.

__Solution:__
* `v$<Cr>` will select "__Test Test__" without the newline
* `<Cr>` will select "__Test__ Test" and give you

```
[Test](Test) Test
```
                        
### 2 vw

__w__ is moving the cursor to the begining of the next word. And visual selection is inclugin  the chactarer in the cursor position so you are selecting "__Test T__ est". Meaning you are including the next "T" in the selection. You can press `x` to delete the selection and confirm it. So this gives the observed behavior which is to `transform all the selection in a link`

__Solution:__
* `e<Cr>` whitch select "__Test__Test" (only the first word)
* '<Cr>` also selecting a word by default 

### 3 Notations

`<S-V>` = shift+V ; `<Cr>` = Carriage REturn (enter keypress)

Note: I close but feel free to comment or reopen

**Comment by sharingtom** [comment]
Thanks! This makes sense. I'm fairly new to Vim so I'm not familiar with all the keybindings yet.
