### ISSUE TITLE
vimwiki with vinegar

### ISSUE THREAD

**Issue by juev** [vimwiki/vimwiki#937]
VimWiki
Stable version: 2.5

Settings:
```vim
" Settings for Vimwiki
let g:vimwiki_list = [{'path':'~/Dropbox/vimwiki/'}]
" let g:vimwiki_list = [{'path':'~/Dropbox/vimwiki/markdown/','ext':'.md','syntax':'markdown'}, {"path":"~/Dropbox/vimwiki/wiki/"}]
let g:zettel_fzf_command = "rg --column --line-number --ignore-case --no-heading --color=always "
let g:zettel_format = "%y%m%d%H%M"
```

By default in vimwiki buffers we have mapping '-' key to `<Plug>VimwikiRemoveHeaderLevel`.

I'm using tpope/vim-vinegar plugin for fast navigating on filesystem. This plugin used the same mapping '-' for `VinegarUp`.

How I can use only mapping from vim-vinegar for key '-'? Is it possible.

Sorry for the possibly stupid question. 😞

**Comment by mifegui** [comment]
You can remap `<Plug>VimwikiRemoveHeaderLevel`, in your vimrc, with
```
nmap <Nop> <Plug>VimwikiRemoveHeaderLevel
```

`<Nop>` Means nothing (so you can't use this function anymore),
Instead of `<Nop>` you could put some other mapping like `<Leader>-` 

You could see this in `:help vimwiki-mappings`

With that the vinegar map *should* work.

You can use the same syntax to any other plugin that has this `<Plug>` thing.

**Comment by juev** [comment]
Thank you very much!
It's worked!
