### ISSUE TITLE
jump to the next TODO item

### ISSUE THREAD

**Issue by llinfeng** [vimwiki/vimwiki#94]
Not sure if this had been implemented already. Here goes the mappings I used to jump to the next TODO item.

```
nnoremap <S-F10> /\* \[ \]<CR>6l:nohl<CR>
inoremap <S-F10> /\* \[ \]<CR>6l:nohl<CR>i
```

**Comment by ranebrown** [comment]
@hq6 Isn't this something that you had working? What was your implementation?

**Comment by hq6** [comment]
@ranebrown , Yes, I do have a local commit that does this, but I think we weren't sure what the right default keymapping was. Any thoughts on what the key mapping should be?

**Comment by ranebrown** [comment]
I think `glt` makes sense since it follows the same format as the other list commands and isn't currently being used. Your suggestion does has a better mnemonic though. Since it can be customized I don't think it makes too big of a difference.

Do you want to pick one and make this change?

**Comment by hq6** [comment]
@ranebrown I just looked at that commit and realized that it is not in a state that I would be comfortable putting it into `dev` or even making a PR. The main problem is that my search for tasks is not robust, due to lack of support for finding checkboxes in `autoload/vimwiki/vars.vim`.

I can dig into that and add that support, but it's going to be more time-consuming than simply pushing a commit.
