### ISSUE TITLE
Add support to execute vimscript from a link inside vimwiki

### ISSUE THREAD

**Issue by iandstanley** [vimwiki/vimwiki#955]
I can’t find it if it is there .... so assuming that it isn’t ....

Could we add the facility to execute vimscript commands from links entered inside vimwiki?

This would allow us to put more power into what is essentially just a static document

**Comment by tinmarino** [comment]
It do not exists already. This kind of feature needs some discussion. Do you have something to propose like:
- Adding a dict `vimwiki_auto_excute = {fileentension: sh, regex "----\(this_will_be executed\)----"}` so the configuration and security is relayed to the user.
- Add hook to some function like `let g:wimwiki_at_line_enter = function('my_defined_function')`

Related: #854 #860

PS: This is actually supper easy to implement once we agree on a method: I vote for a hook system so that we let all the code responsibility to the user and can show some example in the doc. What about you @iandstanley

**Comment by iandstanley** [comment]
What I’d like to do is in a similar manner to the interWiki page linking 

( “Vimscript code to be evaluated” |  description )

Not fussed about what delimiters/brackets are used. 
But the possibilities of a < “vimscript string” | description > would allow me to put in simple things or exec a vimscript function call that is defined in the .vimrc and would allow me to create intelligent documentation and also build in examples particularly if I then combine with plugins that automate terminal access/exec


> On 25 Jul 2020, at 17:35, Tinmarino <notifications@github.com> wrote:
> 
> ﻿
> It do not exists already. This kind of feature needs some discussion. Do you have something to propose like:
> 
> Adding a dict vimwiki_auto_excute = {fileentension: sh, regex "----\(this_will_be executed\)----"} so the configuration and security is relayed to the user.
> Add hook to some function like let g:wimwiki_at_line_enter = function('my_defined_function')
> Related: #854 #860
> 
> PS: This is actually supper easy to implement once we agree on a method: I vote for a hook system so that we let all the code responsibility to the user and can show some example in the doc. What about you @iandstanley
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- Email domain proudly hosted at https://migadu.com

**Comment by tinmarino** [comment]
It should just not add additional parsing for people not using the feature so the regex you showed me is ok but must enter in a conf that if not present, nothing happens

**Comment by iandstanley** [comment]
Sounds good 
I would be happy for it to require a conf variable set in .vimrc to enable say something like 

set vimwiki-vimscript-embed = 1


> On 25 Jul 2020, at 18:35, Tinmarino <notifications@github.com> wrote:
> 
> ﻿
> It should just not add additional parsing for people not using the feature so the regex you showed me is ok but must enter in a conf that if not present, nothing happens
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- Email domain proudly hosted at https://migadu.com

**Comment by tinmarino** [comment]
> set vimwiki-vimscript-embed = 1

I prefer not a boolean variable : it offers to little customization. Better a __regex__ : `vimwiki-vimscript-embed = '^( \(  .* \) | description ) '` and the code in the first captured group (`\1`) will be executed.
For example, I would also like:

1. Code in the yml header tagged `-vimwikiscript` to be executed on BufferEnter and custom command so user can have a custom preparser called with a system command call async in a vim script 
2. Some lines to be executed and the result replaced at \2 so that for example a user can make command example and get the result at the end
3. The last Table column and line with title `Total` or any word / regex to be filled with the total of the other

All those examples are very heavy of course so will stay under the user responsibility, but we should consider more than one use case seeing the number of users for the maintenance to worth it.

> This would allow us to put more power into what is essentially just a static document

That is a cool. So I really like the __hook__ system because it permits the explosion of combinations of users desires:
The user register: 1/ __when__, 2/ __where__ and 3/ __what__

**Comment by tinmarino** [comment]
All that said, the hook system is not so hard to implement, just to call at registered times the registered scripts at the places registered with a regex.

To start with, you can code an AutoCmd on BufferEnter for filetype vimwiki searching for the places you want and calling the function you like. If so, please paste your code here :-)

**Comment by iandstanley** [comment]
Sounds good

> On 27 Jul 2020, at 04:41, Tinmarino <notifications@github.com> wrote:
> 
> ﻿
> set vimwiki-vimscript-embed = 1
> 
> I prefer not a boolean variable : it offers to little customization. Better a regex : vimwiki-vimscript-embed = '^( \( .* \) | description ) ' and the code in the first captured group (\1) will be executed.
> For example, I would also like:
> 
> Code in the yml header tagged -vimwikiscript to be executed on BufferEnter and custom command so user can have a custom preparser called with a system command call async in a vim script
> Some lines to be executed and the result replaced at \2 so that for example a user can make command example and get the result at the end
> The last Table column and line with title Total or any word / regex to be filled with the total of the other
> All those examples are very heavy of course so will stay under the user responsibility, but we should consider more than one use case seeing the number of users for the maintenance to worth it.
> 
> This would allow us to put more power into what is essentially just a static document
> 
> That is a cool. So I really like the hook system because it permits the explosion of combinations of users desires:
> The user register: 1/ when, 2/ where and 3/ what
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- Email domain proudly hosted at https://migadu.com

**Comment by brennen** [comment]
See also: #1001 on supporting code execution.

**Comment by brennen** [comment]
Closing this one to consolidate on #1001.
