### ISSUE TITLE
Don't overwrite folding settings

### ISSUE THREAD

**Issue by t7ko** [vimwiki/vimwiki#97]
Currently, folding settings are controlled by a global var, `g:vimwiki_folding`.  

I have a use case, in which I want to have folding by header in all pages in wiki, and folding by list level in some specific pages (which will generally be a todo lists).

One way to have it is to support per-page folding settings.  Which could be done by something like Vim's modelines.  What do you guys think?

**Comment by EinfachToll** [comment]
The obvious solution is to just use a modeline to set the foldmethod. But I remember that it doesn't work because Vimwiki overwrites the setting.

**Comment by t7ko** [comment]
I don't know...  I haven't looked into code yet, but from looking at the docs, I thought, vim `'foldmethod'` is to choose the "engine" (syntax vs expr), and `g:vimwiki_folding` should be used to tell what to fold (headers vs lists).  Plus, `g:vimwiki_folding` supports `'list'` option which is not accepted for `'foldmethod'`.  So they are different.

My first idea was to implement some kind of `vimwiki:` modeline similar to `vim:` modelines, and support setting vimwiki settings from those modelines on a per-page basis.

**Comment by ches** [comment]
@t7ko [Here][1] is how the names of the `g:vimwiki_folding` values map to the Vim options. That would make for rather verbose modelines, I'm not sure if Vim's modeline parsing will even allow this, and finally from a glance at the code it looks like Vimwiki will probably override it anyway like @EinfachToll suggests.

But it seems like there could be a workaround, though maybe a little tedious... you can initially tell Vimwiki not to set any folding, then:

```vim
" Tell Vimwiki to let me decide manually
let g:vimwiki_folding = ''

" Default to Vimwiki's section folding options
autocmd FileType vimwiki setlocal
      \ fdm=expr
      \ foldexpr=VimwikiFoldLevel(v:lnum)
      \ foldtext=VimwikiFoldText()

" Use the list folding options in some places
autocmd BufRead,BufNewFile my/todo/pages/*.wiki setlocal
      \ fdm=expr
      \ foldexpr=VimwikiFoldListLevel(v:lnum)
      \ foldtext=VimwikiFoldText()
```

Of course that assumes that you can fit your organization to some matchable pattern or else it would otherwise become a pain to match specific pages, but maybe that gives you a start to play with.

[1]: https://github.com/vimwiki/vimwiki/blob/2c03d82a0e4662adf1e347487d73a9bf4bf6fdac/plugin/vimwiki.vim#L197-L211

**Comment by EinfachToll** [comment]
This is solved in the meantime. You can set g:vimwiki_folding to 'custom'.
