### ISSUE TITLE
Feature request: highlight multiline selection

### ISSUE THREAD

**Issue by VimWei** [vimwiki/vimwiki#990]
I use vimwiki md syntax daily.

I can use bold and italic syntax. But they can only affect single line and not very easy to notice .

Can we highlight multiline just like microsoft word: select / highlight.

![image](https://user-images.githubusercontent.com/25874852/90847457-22b6d700-e39d-11ea-9a76-3b23ac6d57d6.png)

**Comment by tinmarino** [comment]
Hi @VimWei 
I love this feature request.
I would implement this with the `font` or `spam` html tag that is concealed. Then Vim does what it can to figure the color parsing the style.

**Comment by tinmarino** [comment]
Hi @VimWei 
I love this feature request.
I would implement this with the `font` or `spam` html tag that is concealed. Then Vim does what it can to figure the color parsing the style.

**Comment by tinmarino** [comment]
So we can copy https://txtfmt.webs.com for the html tags
Or implement text-properties for vim versions > 8.2 but this last may worth another plugin.
In any case, this may require huge amount of work

**Comment by VimWei** [comment]
Cool! Thanks!

**Comment by tinmarino** [comment]
@VimWei, I recently push the first commit. `VimwikiColorize red` to color the current line in red. I inform you so that we agree about what is next.

1. Can highlight multiple lines (2h)
2. Better handling of the color_tag_template (1h)
3. Add mapping, if possible with a popup window to inform what color is possible like `,wc` for leader wiki colorize and then `r` for red and `br` for background red and if there is nothing starting with r, the command is launched so you just type `,wcby` to colorize with a yellow background (4h due to the popup menu: I take this one)
4. Remove TODO in doc
5. Add tests (2h), screenshots here
6. Integrate #948 to the map so that `,wcb` gives bold and `,wci` surrounds with italic
7. Close this issue.

As usual, I overestimate the time, so that I feel fast in the end hahaha. 
It should be done by my services within 2 weeks.
Can you give me a feedback abound what there is.

AH I almost forgot, you must `set termguicolors` because the 24 colors of the terminal are (very) annoying to map to html hex
* Optional TODO: hard paste a Hex2TermColor function from an other plugin

**Comment by VimWei** [comment]
I've tried the update. It's cool, thanks!

Can we just highlight the selection part but not whole line? Otherwise perfect.

**Comment by tinmarino** [comment]
I just finished implemented the feature, by default mapped to `<Leaderwc` see `:h vimwiki_<Leader>wc`.

![Uploading Screenshot-2021-01-10-19_25_29.png…]()

**Comment by kLabz** [comment]
Hi, why has this been added to `links` key mappings?

I know I can just remap `<Plug>VimwikiColorizeNormal` and `<Plug>VimwikiColorize` but it still feels weird to have `VimwikiColorize` mappings be added by enabling `links` key mappings
