### ISSUE TITLE
Syntax not getting set to markdown

### ISSUE THREAD

**Issue by patdavid** [vimwiki/vimwiki#998]
I'm using vimwiki and a couple of other extensions for writing (pencil, pencil colorscheme, plasticboy vim-markdown).
I setup my vimwiki in .vimrc to use markdown:
```
let g:vimwiki_list = [{'path': '~/Nextcloud/vimwiki/', 
			\ 'path_html': '~/Nextcloud/vimwiki/export/html',
			\ 'syntax': 'markdown', 
			\ 'ext': '.md',
                        \ 'auto_diary_index': 1,
			\ 'auto_tags': 1}]
```
vimwiki seems to work just fine, but checking `:set syntax` shows `syntax=vimwiki`. :(

This is usually fine, but it borks the colorscheme I'm using.  Setting the syntax manually `:set syntax=markdown` does get the colorscheme working correctly, but I have a couple of questions:
1. Is this expected behavior?  Shouldn't the `'syntax': 'markdown'` option set the syntax for all wiki pages correctly?
2. Is it safe to manually set the syntax, or will that break some functionality in vimwiki I'm not aware of yet?
Prior to submitting a new issue make sure to complete these steps:

- [x] Include the output of `:VimwikiShowVersion`.
`Stable version: 2.5`

**Comment by tinmarino** [comment]
1. Yes it is the expected behavior. Setting syntax: markdown is "just" an internal vimwiki variable that tells vimwiki how to highlight this vimwiki file. But the filetype must be vimwiki (no trabsgression easily possible here because many things happens in ftplugin). Concerning the syntax vim option, things are less strict. Which leads to 2
2. Setting vim syntax is "allowed". You must be clear what syntax you want and not mix the two: if two plugins are highlithing your code, for example one and then an other, many things will break and you will get vim errors while scrolling.

That is why syntax file begins with
```vim
if exists('b:current_syntax')
  finish
endif
```
So in ftplugin/vimwiki.vim you can add `let b:current_syntax =1` to forbid the syntax loading. Then you unlet it and `set syntax = markdown`
This should work if there is no bug in any plugin.

**Comment by tinmarino** [comment]
Actualky just set syntax = markdown soon enought will set the b:current_syntax and forbig vimwiki's highlighting

**Comment by patdavid** [comment]
Aha, I think I've found it.  Everything I reported seems to be working as expected.

My problem was with getting `syntax=markdown` on the file, and I found I could set it through the `~/.vim/after/ftplugin/vimwiki.vim` by setting:

```
au BufEnter *.md setl syntax=markdown
```

Now my syntax is correct - thank you for the help!
